import { NextRequest, NextResponse } from 'next/server';
import { ensureSchema, getSql } from '@/lib/db';
import { requireAdmin } from '@/lib/server/auth/admin';
import { getGmailClient } from '@/lib/server/gmail-client';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const SENDER = 'support@fastemail.email';
type Details = { agentName: string | null; company: string | null; businessAddress: string | null; email: string | null; website: string | null; phone: string | null };

async function setup() {
  await ensureSchema();
  const sql = getSql();
  await sql`CREATE TABLE IF NOT EXISTS fastemail_realtor_imports (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), gmail_message_id TEXT NOT NULL UNIQUE, received_at TIMESTAMPTZ NOT NULL, agent_name TEXT, company TEXT, business_address TEXT, email TEXT, website TEXT, phone TEXT, status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','realtyline','san_antonio','rejected')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), reviewed_at TIMESTAMPTZ)`;
  await sql`CREATE INDEX IF NOT EXISTS fastemail_realtor_imports_status_idx ON fastemail_realtor_imports(status, received_at DESC)`;
}
function decode(v?: string | null) { return v ? Buffer.from(v, 'base64url').toString('utf8') : ''; }
function body(message: any) { const plain: string[] = []; const html: string[] = []; const visit = (part: any) => { if (!part) return; const value = decode(part.body?.data); if (value) ((part.mimeType || '').toLowerCase() === 'text/plain' ? plain : html).push(value); for (const child of part.parts || []) visit(child); }; visit(message.payload); return (plain.join('\n') || html.join('\n').replace(/<[^>]+>/g, ' ')).replace(/&nbsp;/gi, ' ').replace(/&amp;/gi, '&').replace(/\s+/g, ' ').trim(); }
function clean(value: string | null | undefined) { const text = value?.replace(/\s+/g, ' ').trim(); return text || null; }
function extract(raw: string): Details { const end = raw.search(/Information deemed reliable|INSTANT REMOVAL LINK|This property listing was sent/i); const text = (end >= 0 ? raw.slice(0, end) : raw).slice(-2200); const emails = Array.from(text.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)).map((m) => m[0]).filter((v) => v.toLowerCase() !== SENDER); const email = emails.at(-1) || null; const website = Array.from(text.matchAll(/(?:https?:\/\/)?(?:www\.)?[a-z0-9-]+(?:\.[a-z0-9-]+)+\.[a-z]{2,}(?:\/[^\s]*)?/gi)).map((m) => m[0]).find((v) => !v.includes('fastemail')) || null; const phone = Array.from(text.matchAll(/(?:\+1[ .-]?)?(?:\(?\d{3}\)?[ .-]?)\d{3}[ .-]\d{4}/g)).map((m) => m[0]).at(-1) || null; const beforeEmail = email ? text.slice(0, text.lastIndexOf(email)) : text; const addressMatch = beforeEmail.match(/([\s\S]{0,180}?\b\d{1,6}\s+[^\n]{3,100}?\b(?:TX|Texas)\s+\d{5}(?:-\d{4})?\b)/i); const businessAddress = clean(addressMatch?.[1]?.split(/(?<=\d{5})/)[0] || null); const prior = addressMatch ? beforeEmail.slice(Math.max(0, addressMatch.index! - 450), addressMatch.index) : beforeEmail.slice(-450); const chunks = prior.split(/(?<=[.!?])\s+(?=[A-Z])/).map(clean).filter(Boolean) as string[]; const agentLine = chunks.reverse().find((v) => /REALTOR|Broker|Associate/i.test(v)) || null; const agentName = clean(agentLine?.replace(/,?\s*(REALTOR|Broker(?:\/Owners?)?|Associate|ABR|CRB|CRS|GRI|SRS|RENE|CLHMS|RSPS|Luxury Specialist|Accredited Staging Professional).*/gi, '') || null); const company = clean(chunks.find((v) => v !== agentLine && /Realty|RE\/MAX|Properties|Real Estate|Realtors|Brokerage|Homes/i.test(v)) || null); return { agentName, company, businessAddress, email, website: clean(website), phone: clean(phone) }; }

export async function GET(req: NextRequest) { await requireAdmin(); await setup(); const status = new URL(req.url).searchParams.get('status') || 'pending'; const sql = getSql(); const rows = status === 'all' ? await sql`SELECT * FROM fastemail_realtor_imports ORDER BY received_at DESC` : await sql`SELECT * FROM fastemail_realtor_imports WHERE status = ${status} ORDER BY received_at DESC`; const countRows = await sql`SELECT status, count(*)::int AS count FROM fastemail_realtor_imports GROUP BY status` as unknown as Array<{status: string; count: number}>; return NextResponse.json({ rows, counts: Object.fromEntries(countRows.map((r) => [r.status, r.count])) }); }
export async function POST() { await requireAdmin(); await setup(); const client = await getGmailClient(); if (!client) return NextResponse.json({ error: 'Connect Gmail before scanning.' }, { status: 400 }); const sql = getSql(); const listed = await client.gmail.users.messages.list({ userId: 'me', q: `from:${SENDER}`, maxResults: 100 }); let queued = 0, skipped = 0; for (const item of listed.data.messages || []) { if (!item.id) continue; const known = await sql`SELECT id FROM fastemail_realtor_imports WHERE gmail_message_id = ${item.id} LIMIT 1`; if ((known as unknown[]).length) { skipped++; continue; } const message = await client.gmail.users.messages.get({ userId: 'me', id: item.id, format: 'full' }); const d = extract(body(message.data)); if (!d.agentName && !d.email) { skipped++; continue; } const received = message.data.internalDate ? new Date(Number(message.data.internalDate)) : new Date(); await sql`INSERT INTO fastemail_realtor_imports (gmail_message_id, received_at, agent_name, company, business_address, email, website, phone) VALUES (${item.id}, ${received}, ${d.agentName}, ${d.company}, ${d.businessAddress}, ${d.email}, ${d.website}, ${d.phone}) ON CONFLICT (gmail_message_id) DO NOTHING`; queued++; } return NextResponse.json({ queued, skipped }); }
export async function PATCH(req: NextRequest) { await requireAdmin(); await setup(); const { id, action } = await req.json() as { id?: string; action?: 'realtyline' | 'san_antonio' | 'reject' }; if (!id || !['realtyline','san_antonio','reject'].includes(action || '')) return NextResponse.json({ error: 'A valid record and action are required.' }, { status: 400 }); const sql = getSql(); const found = await sql`SELECT * FROM fastemail_realtor_imports WHERE id = ${id} LIMIT 1` as unknown as any[]; const row = found[0]; if (!row) return NextResponse.json({ error: 'Record not found.' }, { status: 404 }); if (action === 'reject') { await sql`UPDATE fastemail_realtor_imports SET status = 'rejected', reviewed_at = NOW() WHERE id = ${id}`; return NextResponse.json({ ok: true }); } const segment = action === 'realtyline' ? 'realtyline-atx-print' : 'newsline-sa-print'; const exists = row.email ? await sql`SELECT id FROM mailing_contacts WHERE lower(email) = lower(${row.email}) LIMIT 1` : []; const duplicate = (exists as unknown[]).length > 0; if (!duplicate) { const name = String(row.agent_name || '').trim().split(/\s+/); await sql`INSERT INTO mailing_contacts (segment, first_name, last_name, email, phone, company, address, website, source, tags) VALUES (${segment}, ${name[0] || '(no name)'}, ${name.slice(1).join(' ') || null}, ${row.email}, ${row.phone}, ${row.company}, ${row.business_address}, ${row.website}, 'fastemail', ${JSON.stringify(['REALTOR','fastemail'])}::jsonb)`; } await sql`UPDATE fastemail_realtor_imports SET status = ${action}, reviewed_at = NOW() WHERE id = ${id}`; return NextResponse.json({ ok: true, duplicate }); }
