/** Candidate integrations by category (up to 25 each). Only those Composio supports with managed sign-in are shown. */
export type CatalogEntry = { toolkit: string; name: string; group: string };

export const CATALOG: CatalogEntry[] = [
  { toolkit: 'dropbox_sign', name: 'Dropbox Sign', group: 'E-Signature' },
  { toolkit: 'pandadoc', name: 'PandaDoc', group: 'E-Signature' },
  { toolkit: 'boldsign', name: 'BoldSign', group: 'E-Signature' },
  { toolkit: 'signnow', name: 'signNow', group: 'E-Signature' },
  { toolkit: 'adobe_sign', name: 'Adobe Sign', group: 'E-Signature' },
  { toolkit: 'signwell', name: 'SignWell', group: 'E-Signature' },
  { toolkit: 'zoho_sign', name: 'Zoho Sign', group: 'E-Signature' },
  { toolkit: 'esignatures_io', name: 'eSignatures.io', group: 'E-Signature' },
  { toolkit: 'docuseal', name: 'DocuSeal', group: 'E-Signature' },
  { toolkit: 'jotform', name: 'Jotform', group: 'E-Signature' },
  { toolkit: 'formstack', name: 'Formstack', group: 'E-Signature' },
  { toolkit: 'anvil', name: 'Anvil', group: 'E-Signature' },
  { toolkit: 'foxit_esign', name: 'Foxit eSign', group: 'E-Signature' },
  { toolkit: 'signaturely', name: 'Signaturely', group: 'E-Signature' },
  { toolkit: 'airslate', name: 'airSlate', group: 'E-Signature' },
  { toolkit: 'airslate_signnow', name: 'airSlate SignNow', group: 'E-Signature' },
  { toolkit: 'legalesign', name: 'Legalesign', group: 'E-Signature' },
  { toolkit: 'yousign', name: 'Yousign', group: 'E-Signature' },
  { toolkit: 'zapsign', name: 'ZapSign', group: 'E-Signature' },
  { toolkit: 'mobilesign', name: 'MobileSign', group: 'E-Signature' },
  { toolkit: 'revv', name: 'Revv', group: 'E-Signature' },
  { toolkit: 'sertifi', name: 'Sertifi', group: 'E-Signature' },
  { toolkit: 'docsketch', name: 'DocSketch', group: 'E-Signature' },
  { toolkit: 'esign_genie', name: 'eSignGenie', group: 'E-Signature' },
  { toolkit: 'googlecalendar', name: 'Google Calendar', group: 'Calendar and Scheduling' },
  { toolkit: 'outlook', name: 'Outlook', group: 'Calendar and Scheduling' },
  { toolkit: 'calendly', name: 'Calendly', group: 'Calendar and Scheduling' },
  { toolkit: 'cal', name: 'Cal.com', group: 'Calendar and Scheduling' },
  { toolkit: 'acuity_scheduling', name: 'Acuity Scheduling', group: 'Calendar and Scheduling' },
  { toolkit: 'zoom', name: 'Zoom', group: 'Calendar and Scheduling' },
  { toolkit: 'microsoft_teams', name: 'Microsoft Teams', group: 'Calendar and Scheduling' },
  { toolkit: 'googlemeet', name: 'Google Meet', group: 'Calendar and Scheduling' },
  { toolkit: 'microsoft_bookings', name: 'Microsoft Bookings', group: 'Calendar and Scheduling' },
  { toolkit: 'savvycal', name: 'SavvyCal', group: 'Calendar and Scheduling' },
  { toolkit: 'setmore', name: 'Setmore', group: 'Calendar and Scheduling' },
  { toolkit: 'square_appointments', name: 'Square Appointments', group: 'Calendar and Scheduling' },
  { toolkit: 'calendarhero', name: 'CalendarHero', group: 'Calendar and Scheduling' },
  { toolkit: 'doodle', name: 'Doodle', group: 'Calendar and Scheduling' },
  { toolkit: 'tidycal', name: 'TidyCal', group: 'Calendar and Scheduling' },
  { toolkit: 'youcanbookme', name: 'YouCanBook.me', group: 'Calendar and Scheduling' },
  { toolkit: 'appointlet', name: 'Appointlet', group: 'Calendar and Scheduling' },
  { toolkit: 'simplybook_me', name: 'SimplyBook.me', group: 'Calendar and Scheduling' },
  { toolkit: 'zoho_bookings', name: 'Zoho Bookings', group: 'Calendar and Scheduling' },
  { toolkit: 'webex', name: 'Webex', group: 'Calendar and Scheduling' },
  { toolkit: 'gotomeeting', name: 'GoToMeeting', group: 'Calendar and Scheduling' },
  { toolkit: 'whereby', name: 'Whereby', group: 'Calendar and Scheduling' },
  { toolkit: 'addevent', name: 'AddEvent', group: 'Calendar and Scheduling' },
  { toolkit: 'google_tasks', name: 'Google Tasks', group: 'Calendar and Scheduling' },
  { toolkit: 'fantastical', name: 'Fantastical', group: 'Calendar and Scheduling' },
  { toolkit: 'gmail', name: 'Gmail', group: 'Email' },
  { toolkit: 'mailchimp', name: 'Mailchimp', group: 'Email' },
  { toolkit: 'sendgrid', name: 'SendGrid', group: 'Email' },
  { toolkit: 'brevo', name: 'Brevo', group: 'Email' },
  { toolkit: 'activecampaign', name: 'ActiveCampaign', group: 'Email' },
  { toolkit: 'constant_contact', name: 'Constant Contact', group: 'Email' },
  { toolkit: 'klaviyo', name: 'Klaviyo', group: 'Email' },
  { toolkit: 'mailgun', name: 'Mailgun', group: 'Email' },
  { toolkit: 'postmark', name: 'Postmark', group: 'Email' },
  { toolkit: 'resend', name: 'Resend', group: 'Email' },
  { toolkit: 'convertkit', name: 'Kit (ConvertKit)', group: 'Email' },
  { toolkit: 'aweber', name: 'AWeber', group: 'Email' },
  { toolkit: 'campaign_monitor', name: 'Campaign Monitor', group: 'Email' },
  { toolkit: 'getresponse', name: 'GetResponse', group: 'Email' },
  { toolkit: 'drip', name: 'Drip', group: 'Email' },
  { toolkit: 'mailerlite', name: 'MailerLite', group: 'Email' },
  { toolkit: 'moosend', name: 'Moosend', group: 'Email' },
  { toolkit: 'benchmark_email', name: 'Benchmark Email', group: 'Email' },
  { toolkit: 'sendinblue', name: 'Sendinblue', group: 'Email' },
  { toolkit: 'mandrill', name: 'Mandrill', group: 'Email' },
  { toolkit: 'amazon_ses', name: 'Amazon SES', group: 'Email' },
  { toolkit: 'hunter', name: 'Hunter', group: 'Email' },
  { toolkit: 'zerobounce', name: 'ZeroBounce', group: 'Email' },
  { toolkit: 'instantly', name: 'Instantly', group: 'Email' },
  { toolkit: 'lemlist', name: 'lemlist', group: 'Email' },
  { toolkit: 'googledrive', name: 'Google Drive', group: 'Documents and Storage' },
  { toolkit: 'dropbox', name: 'Dropbox', group: 'Documents and Storage' },
  { toolkit: 'one_drive', name: 'OneDrive', group: 'Documents and Storage' },
  { toolkit: 'box', name: 'Box', group: 'Documents and Storage' },
  { toolkit: 'share_point', name: 'SharePoint', group: 'Documents and Storage' },
  { toolkit: 'googledocs', name: 'Google Docs', group: 'Documents and Storage' },
  { toolkit: 'googlesheets', name: 'Google Sheets', group: 'Documents and Storage' },
  { toolkit: 'notion', name: 'Notion', group: 'Documents and Storage' },
  { toolkit: 'airtable', name: 'Airtable', group: 'Documents and Storage' },
  { toolkit: 'excel', name: 'Microsoft Excel', group: 'Documents and Storage' },
  { toolkit: 'onenote', name: 'OneNote', group: 'Documents and Storage' },
  { toolkit: 'evernote', name: 'Evernote', group: 'Documents and Storage' },
  { toolkit: 'coda', name: 'Coda', group: 'Documents and Storage' },
  { toolkit: 'confluence', name: 'Confluence', group: 'Documents and Storage' },
  { toolkit: 'google_slides', name: 'Google Slides', group: 'Documents and Storage' },
  { toolkit: 'word', name: 'Microsoft Word', group: 'Documents and Storage' },
  { toolkit: 'pcloud', name: 'pCloud', group: 'Documents and Storage' },
  { toolkit: 'egnyte', name: 'Egnyte', group: 'Documents and Storage' },
  { toolkit: 'sharefile', name: 'ShareFile', group: 'Documents and Storage' },
  { toolkit: 'docparser', name: 'Docparser', group: 'Documents and Storage' },
  { toolkit: 'pdfco', name: 'PDF.co', group: 'Documents and Storage' },
  { toolkit: 'cloudconvert', name: 'CloudConvert', group: 'Documents and Storage' },
  { toolkit: 'adobe', name: 'Adobe', group: 'Documents and Storage' },
  { toolkit: 'canva', name: 'Canva', group: 'Documents and Storage' },
  { toolkit: 'smartsheet', name: 'Smartsheet', group: 'Documents and Storage' },
  { toolkit: 'hubspot', name: 'HubSpot', group: 'CRM and Leads' },
  { toolkit: 'salesforce', name: 'Salesforce', group: 'CRM and Leads' },
  { toolkit: 'pipedrive', name: 'Pipedrive', group: 'CRM and Leads' },
  { toolkit: 'zoho', name: 'Zoho CRM', group: 'CRM and Leads' },
  { toolkit: 'followupboss', name: 'Follow Up Boss', group: 'CRM and Leads' },
  { toolkit: 'cinc', name: 'CINC', group: 'CRM and Leads' },
  { toolkit: 'realgeeks', name: 'RealGeeks', group: 'CRM and Leads' },
  { toolkit: 'gohighlevel', name: 'HighLevel', group: 'CRM and Leads' },
  { toolkit: 'zendesk_sell', name: 'Zendesk Sell', group: 'CRM and Leads' },
  { toolkit: 'close', name: 'Close', group: 'CRM and Leads' },
  { toolkit: 'copper', name: 'Copper', group: 'CRM and Leads' },
  { toolkit: 'freshsales', name: 'Freshsales', group: 'CRM and Leads' },
  { toolkit: 'keap', name: 'Keap', group: 'CRM and Leads' },
  { toolkit: 'insightly', name: 'Insightly', group: 'CRM and Leads' },
  { toolkit: 'attio', name: 'Attio', group: 'CRM and Leads' },
  { toolkit: 'capsule_crm', name: 'Capsule CRM', group: 'CRM and Leads' },
  { toolkit: 'nutshell', name: 'Nutshell', group: 'CRM and Leads' },
  { toolkit: 'agile_crm', name: 'Agile CRM', group: 'CRM and Leads' },
  { toolkit: 'sugarcrm', name: 'SugarCRM', group: 'CRM and Leads' },
  { toolkit: 'streak', name: 'Streak', group: 'CRM and Leads' },
  { toolkit: 'apollo', name: 'Apollo', group: 'CRM and Leads' },
  { toolkit: 'lofty', name: 'Lofty', group: 'CRM and Leads' },
  { toolkit: 'boomtown', name: 'BoomTown', group: 'CRM and Leads' },
  { toolkit: 'wise_agent', name: 'Wise Agent', group: 'CRM and Leads' },
  { toolkit: 'sierra_interactive', name: 'Sierra Interactive', group: 'CRM and Leads' },
  { toolkit: 'slack', name: 'Slack', group: 'Messaging and Calls' },
  { toolkit: 'twilio', name: 'Twilio', group: 'Messaging and Calls' },
  { toolkit: 'telnyx', name: 'Telnyx', group: 'Messaging and Calls' },
  { toolkit: 'discord', name: 'Discord', group: 'Messaging and Calls' },
  { toolkit: 'telegram', name: 'Telegram', group: 'Messaging and Calls' },
  { toolkit: 'whatsapp', name: 'WhatsApp', group: 'Messaging and Calls' },
  { toolkit: 'ringcentral', name: 'RingCentral', group: 'Messaging and Calls' },
  { toolkit: 'openphone', name: 'OpenPhone', group: 'Messaging and Calls' },
  { toolkit: 'intercom', name: 'Intercom', group: 'Messaging and Calls' },
  { toolkit: 'aircall', name: 'Aircall', group: 'Messaging and Calls' },
  { toolkit: 'dialpad', name: 'Dialpad', group: 'Messaging and Calls' },
  { toolkit: 'vonage', name: 'Vonage', group: 'Messaging and Calls' },
  { toolkit: 'plivo', name: 'Plivo', group: 'Messaging and Calls' },
  { toolkit: 'messagebird', name: 'MessageBird', group: 'Messaging and Calls' },
  { toolkit: 'sinch', name: 'Sinch', group: 'Messaging and Calls' },
  { toolkit: 'textmagic', name: 'TextMagic', group: 'Messaging and Calls' },
  { toolkit: 'callrail', name: 'CallRail', group: 'Messaging and Calls' },
  { toolkit: 'justcall', name: 'JustCall', group: 'Messaging and Calls' },
  { toolkit: 'zendesk', name: 'Zendesk', group: 'Messaging and Calls' },
  { toolkit: 'freshdesk', name: 'Freshdesk', group: 'Messaging and Calls' },
  { toolkit: 'front', name: 'Front', group: 'Messaging and Calls' },
  { toolkit: 'helpscout', name: 'Help Scout', group: 'Messaging and Calls' },
  { toolkit: 'drift', name: 'Drift', group: 'Messaging and Calls' },
  { toolkit: 'podium', name: 'Podium', group: 'Messaging and Calls' },
  { toolkit: 'textline', name: 'Textline', group: 'Messaging and Calls' },
  { toolkit: 'dotloop', name: 'Dotloop', group: 'Real Estate' },
  { toolkit: 'skyslope', name: 'SkySlope', group: 'Real Estate' },
  { toolkit: 'zillow', name: 'Zillow', group: 'Real Estate' },
  { toolkit: 'realtor', name: 'Realtor.com', group: 'Real Estate' },
  { toolkit: 'brokermint', name: 'Brokermint', group: 'Real Estate' },
  { toolkit: 'lone_wolf', name: 'Lone Wolf', group: 'Real Estate' },
  { toolkit: 'showingtime', name: 'ShowingTime', group: 'Real Estate' },
  { toolkit: 'rentcast', name: 'RentCast', group: 'Real Estate' },
  { toolkit: 'attom', name: 'ATTOM', group: 'Real Estate' },
  { toolkit: 'propstream', name: 'PropStream', group: 'Real Estate' },
  { toolkit: 'cotality', name: 'Cotality', group: 'Real Estate' },
  { toolkit: 'homesnap', name: 'Homesnap', group: 'Real Estate' },
  { toolkit: 'bridge_interactive', name: 'Bridge Interactive', group: 'Real Estate' },
  { toolkit: 'spark_api', name: 'Spark API', group: 'Real Estate' },
  { toolkit: 'buildium', name: 'Buildium', group: 'Real Estate' },
  { toolkit: 'appfolio', name: 'AppFolio', group: 'Real Estate' },
  { toolkit: 'rent_manager', name: 'Rent Manager', group: 'Real Estate' },
  { toolkit: 'doorloop', name: 'DoorLoop', group: 'Real Estate' },
  { toolkit: 'propertyware', name: 'Propertyware', group: 'Real Estate' },
  { toolkit: 'matterport', name: 'Matterport', group: 'Real Estate' },
  { toolkit: 'cloudcma', name: 'Cloud CMA', group: 'Real Estate' },
  { toolkit: 'rpr', name: 'RPR', group: 'Real Estate' },
  { toolkit: 'smartzip', name: 'SmartZip', group: 'Real Estate' },
  { toolkit: 'placester', name: 'Placester', group: 'Real Estate' },
  { toolkit: 'quickbooks', name: 'QuickBooks', group: 'Accounting and Payments' },
  { toolkit: 'stripe', name: 'Stripe', group: 'Accounting and Payments' },
  { toolkit: 'xero', name: 'Xero', group: 'Accounting and Payments' },
  { toolkit: 'freshbooks', name: 'FreshBooks', group: 'Accounting and Payments' },
  { toolkit: 'square', name: 'Square', group: 'Accounting and Payments' },
  { toolkit: 'paypal', name: 'PayPal', group: 'Accounting and Payments' },
  { toolkit: 'wave', name: 'Wave', group: 'Accounting and Payments' },
  { toolkit: 'zoho_books', name: 'Zoho Books', group: 'Accounting and Payments' },
  { toolkit: 'bill', name: 'Bill', group: 'Accounting and Payments' },
  { toolkit: 'expensify', name: 'Expensify', group: 'Accounting and Payments' },
  { toolkit: 'brex', name: 'Brex', group: 'Accounting and Payments' },
  { toolkit: 'ramp', name: 'Ramp', group: 'Accounting and Payments' },
  { toolkit: 'plaid', name: 'Plaid', group: 'Accounting and Payments' },
  { toolkit: 'wise', name: 'Wise', group: 'Accounting and Payments' },
  { toolkit: 'chargebee', name: 'Chargebee', group: 'Accounting and Payments' },
  { toolkit: 'gusto', name: 'Gusto', group: 'Accounting and Payments' },
  { toolkit: 'docupilot', name: 'Docupilot', group: 'Accounting and Payments' },
  { toolkit: 'invoiced', name: 'Invoiced', group: 'Accounting and Payments' },
  { toolkit: 'sage', name: 'Sage', group: 'Accounting and Payments' },
  { toolkit: 'netsuite', name: 'NetSuite', group: 'Accounting and Payments' },
  { toolkit: 'paddle', name: 'Paddle', group: 'Accounting and Payments' },
  { toolkit: 'razorpay', name: 'Razorpay', group: 'Accounting and Payments' },
  { toolkit: 'authorize_net', name: 'Authorize.net', group: 'Accounting and Payments' },
  { toolkit: 'braintree', name: 'Braintree', group: 'Accounting and Payments' },
  { toolkit: 'mercury', name: 'Mercury', group: 'Accounting and Payments' },
  { toolkit: 'asana', name: 'Asana', group: 'Tasks and Projects' },
  { toolkit: 'trello', name: 'Trello', group: 'Tasks and Projects' },
  { toolkit: 'clickup', name: 'ClickUp', group: 'Tasks and Projects' },
  { toolkit: 'monday', name: 'monday.com', group: 'Tasks and Projects' },
  { toolkit: 'jira', name: 'Jira', group: 'Tasks and Projects' },
  { toolkit: 'todoist', name: 'Todoist', group: 'Tasks and Projects' },
  { toolkit: 'basecamp', name: 'Basecamp', group: 'Tasks and Projects' },
  { toolkit: 'wrike', name: 'Wrike', group: 'Tasks and Projects' },
  { toolkit: 'linear', name: 'Linear', group: 'Tasks and Projects' },
  { toolkit: 'microsoft_tasks', name: 'Microsoft To Do', group: 'Tasks and Projects' },
  { toolkit: 'teamwork', name: 'Teamwork', group: 'Tasks and Projects' },
  { toolkit: 'height', name: 'Height', group: 'Tasks and Projects' },
  { toolkit: 'productboard', name: 'Productboard', group: 'Tasks and Projects' },
  { toolkit: 'ticktick', name: 'TickTick', group: 'Tasks and Projects' },
  { toolkit: 'any_do', name: 'Any.do', group: 'Tasks and Projects' },
  { toolkit: 'hive', name: 'Hive', group: 'Tasks and Projects' },
  { toolkit: 'podio', name: 'Podio', group: 'Tasks and Projects' },
  { toolkit: 'toggl', name: 'Toggl', group: 'Tasks and Projects' },
  { toolkit: 'harvest', name: 'Harvest', group: 'Tasks and Projects' },
  { toolkit: 'clockify', name: 'Clockify', group: 'Tasks and Projects' },
  { toolkit: 'zenhub', name: 'ZenHub', group: 'Tasks and Projects' },
  { toolkit: 'workamajig', name: 'Workamajig', group: 'Tasks and Projects' },
  { toolkit: 'googleads', name: 'Google Ads', group: 'Marketing and Social' },
  { toolkit: 'facebook', name: 'Facebook', group: 'Marketing and Social' },
  { toolkit: 'instagram', name: 'Instagram', group: 'Marketing and Social' },
  { toolkit: 'linkedin', name: 'LinkedIn', group: 'Marketing and Social' },
  { toolkit: 'twitter', name: 'X (Twitter)', group: 'Marketing and Social' },
  { toolkit: 'youtube', name: 'YouTube', group: 'Marketing and Social' },
  { toolkit: 'googleanalytics', name: 'Google Analytics', group: 'Marketing and Social' },
  { toolkit: 'google_search_console', name: 'Google Search Console', group: 'Marketing and Social' },
  { toolkit: 'google_my_business', name: 'Google Business Profile', group: 'Marketing and Social' },
  { toolkit: 'tiktok', name: 'TikTok', group: 'Marketing and Social' },
  { toolkit: 'pinterest', name: 'Pinterest', group: 'Marketing and Social' },
  { toolkit: 'buffer', name: 'Buffer', group: 'Marketing and Social' },
  { toolkit: 'hootsuite', name: 'Hootsuite', group: 'Marketing and Social' },
  { toolkit: 'sprout_social', name: 'Sprout Social', group: 'Marketing and Social' },
  { toolkit: 'typeform', name: 'Typeform', group: 'Marketing and Social' },
  { toolkit: 'surveymonkey', name: 'SurveyMonkey', group: 'Marketing and Social' },
  { toolkit: 'bitly', name: 'Bitly', group: 'Marketing and Social' },
  { toolkit: 'semrush', name: 'Semrush', group: 'Marketing and Social' },
  { toolkit: 'ahrefs', name: 'Ahrefs', group: 'Marketing and Social' },
  { toolkit: 'yelp', name: 'Yelp', group: 'Marketing and Social' },
  { toolkit: 'wordpress', name: 'WordPress', group: 'Marketing and Social' },
  { toolkit: 'webflow', name: 'Webflow', group: 'Marketing and Social' },
  { toolkit: 'unbounce', name: 'Unbounce', group: 'Marketing and Social' },
  { toolkit: 'later', name: 'Later', group: 'Marketing and Social' },
];
