// lib/advertisers.ts
//
// Shared types and helpers for the advertisers system.

import { randomBytes } from 'crypto';
import type { Publication } from '@/lib/publication-theme';

// ── CRM enums (mirror migration CHECK constraints) ────────────────
export type AdvertiserType   = 'advertiser' | 'client' | 'prospect' | 'mailing';
export type AdvertiserStatus = 'active' | 'prospect' | 'paused' | 'archived';
export type EmailStatus      = 'valid' | 'invalid' | 'risk' | 'unknown';

export type AdditionalContact = {
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  role?: string;
};

export interface Advertiser {
  id: number;
  name: string;
  slug: string;
  share_token: string;
  /**
   * Per-advertiser token for the public event submission form
   * (/submit-event/[submission_token]). Nullable for legacy rows;
   * regenerated by POST /api/admin/advertisers/:id/regenerate-submission-token.
   */
  submission_token?: string | null;
  contact_email: string | null;
  requires_email_gate: boolean;
  /**
   * Which publication this advertiser primarily belongs to.
   * Drives branding on the public dashboard and outbound emails.
   * Optional in the type to remain backward-compatible with rows
   * fetched via SELECT statements that don't include the column;
   * `getPublicationTheme()` always returns a valid theme.
   */
  publication?: Publication;
  created_at: string;
  updated_at: string;

  // ── CRM additions (post 2026_05_29 migration) ───────────────────
  type?: AdvertiserType;
  status?: AdvertiserStatus;

  // Identity
  first_name?: string | null;
  last_name?: string | null;
  company?: string | null;
  title?: string | null;
  industry?: string | null;
  license_number?: string | null;
  avatar_url?: string | null;

  // Channels
  portal_email?: string | null;
  phone?: string | null;
  office_phone?: string | null;
  website?: string | null;

  // Social URLs (Session 18)
  facebook_url?: string | null;
  instagram_url?: string | null;
  linkedin_url?: string | null;
  twitter_url?: string | null;
  youtube_url?: string | null;

  // Public detail page copy (Session 18)
  tagline?: string | null;
  bio?: string | null;

  // Verification
  email_status?: EmailStatus | null;
  email_verified_at?: string | null;

  // Mailing address
  address?: string | null;
  address_2?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;

  // Portal linkage (magic-link client portal)
  portal_activated_at?: string | null;
  portal_onboarded_at?: string | null;

  // Free-form
  additional_contacts?: AdditionalContact[];
  notes?: string | null;
  tags?: string[];
}

// ── Session 19: Locations + Staff ─────────────────────────────────
export interface AdvertiserLocation {
  id: string;
  advertiser_id: number;
  label: string | null;
  address: string | null;
  address_2: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  phone: string | null;
  email: string | null;
  hours: string | null;
  is_primary: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface AdvertiserStaff {
  id: string;
  advertiser_id: number;
  name: string;
  title: string | null;
  email: string | null;
  phone: string | null;
  photo_url: string | null;
  sort_order: number;
  /** IDs of locations this staff member is assigned to (many-to-many). */
  location_ids: string[];
  created_at: string;
  updated_at: string;
}

export const LOCATION_PATCHABLE_FIELDS = [
  'label', 'address', 'address_2', 'city', 'state', 'zip',
  'phone', 'email', 'hours', 'is_primary', 'sort_order',
] as const;
export type LocationPatchableField = (typeof LOCATION_PATCHABLE_FIELDS)[number];

export const STAFF_PATCHABLE_FIELDS = [
  'name', 'title', 'email', 'phone', 'photo_url', 'sort_order',
] as const;
export type StaffPatchableField = (typeof STAFF_PATCHABLE_FIELDS)[number];

export interface AdvertiserWithStats extends Advertiser {
  hotspot_count: number;
  clicks_30d: number;
}

// ── CRM-only stats shape (used by /admin/crm) ─────────────────────
export interface AdvertiserCrmRow extends Advertiser {
  hotspot_count: number;
  clicks_30d: number;
  /** Most recent click timestamp across all of this advertiser's hotspots. */
  last_click_at: string | null;
}

// ── Allow-list of patchable CRM fields ────────────────────────────
// Used by PATCH /api/admin/advertisers/[id] to gate which columns
// clients may write.
export const CRM_PATCHABLE_FIELDS = [
  'type', 'status',
  'first_name', 'last_name', 'company', 'title', 'industry',
  'license_number', 'avatar_url',
  'portal_email', 'phone', 'office_phone', 'website',
  'facebook_url', 'instagram_url', 'linkedin_url', 'twitter_url', 'youtube_url',
  'tagline', 'bio',
  'email_status', 'email_verified_at',
  'address', 'address_2', 'city', 'state', 'zip',
  'portal_activated_at', 'portal_onboarded_at',
  'additional_contacts', 'notes', 'tags',
] as const;

export type CrmPatchableField = (typeof CRM_PATCHABLE_FIELDS)[number];

/** Generate a URL-safe slug from a free-form name. */
export function slugify(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

/** 18-byte (144-bit) url-safe share token. */
export function generateShareToken(): string {
  return randomBytes(18).toString('base64url');
}
