// lib/advertisers.ts
//
// Shared types and helpers for the advertisers system.

import { randomBytes } from 'crypto';
import type { Publication } from '@/lib/publication-theme';
import type { AdvertiserHeaderStyle } from '@/lib/advertiser-header-styles';

// ── CRM enums (mirror migration CHECK constraints) ────────────────
export type AdvertiserType   = 'advertiser' | 'client' | 'prospect' | 'mailing';
export type AdvertiserStatus = 'prospect' | 'advertiser' | 'archived';
type EmailStatus      = 'valid' | 'invalid' | 'risk' | 'unknown';

type AdditionalContact = {
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  role?: string;
};

export interface Advertiser {
  id: number;
  name: string;
  slug: string;
  share_token: string;
  /**
   * Per-advertiser token for the public event submission form
   * (/submit-event/[submission_token]). Nullable for legacy rows;
   * regenerated by POST /api/admin/advertisers/:id/regenerate-submission-token.
   */
  submission_token?: string | null;
  contact_email: string | null;
  requires_email_gate: boolean;
  /**
   * Which publication this advertiser primarily belongs to.
   * Drives branding on the public dashboard and outbound emails.
   * Optional in the type to remain backward-compatible with rows
   * fetched via SELECT statements that don't include the column;
   * `getPublicationTheme()` always returns a valid theme.
   */
  publication?: Publication;
  created_at: string;
  updated_at: string;

  // ── CRM additions (post 2026_05_29 migration) ───────────────────
  type?: AdvertiserType;
  status?: AdvertiserStatus;

  // Identity
  first_name?: string | null;
  last_name?: string | null;
  company?: string | null;
  title?: string | null;
  industry?: string | null;
  license_number?: string | null;
  avatar_url?: string | null;

  // Channels
  portal_email?: string | null;
  phone?: string | null;
  office_phone?: string | null;
  website?: string | null;

  // Social URLs (Session 18)
  facebook_url?: string | null;
  instagram_url?: string | null;
  linkedin_url?: string | null;
  twitter_url?: string | null;
  youtube_url?: string | null;

  // Public detail page copy (Session 18)
  tagline?: string | null;
  bio?: string | null;

  // Header layout for the public detail page. Drop-down on the admin
  // CRM modal lets each advertiser pick its own visual treatment.
  // Defaults to 'current'.
  header_style?: AdvertiserHeaderStyle;
  // ── Marketing outreach + engagement (Session 24) ─────────
  last_contacted_at?: string | null;
  outreach_count?: number | null;
  last_opened_at?: string | null;
  open_count?: number | null;
  last_bounced_at?: string | null;
  bounce_count?: number | null;
  last_bounce_type?: string | null;

  // Default footer template applied to downloadable tools (calculator PDFs).
  // Valid IDs live in lib/footer-templates.ts. The app coerces unknown values
  // back to the default on read.
  footer_template?: string;

  // Verification
  email_status?: EmailStatus | null;
  email_verified_at?: string | null;

  // Company mailing address (Company Details section of the CRM modal)
  address?: string | null;
  address_2?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;

  // Representative mailing address (Representative Details section).
  // Separate from the company address and from per-location addresses
  // tracked in advertiser_locations.
  rep_address?: string | null;
  rep_city?: string | null;
  rep_state?: string | null;
  rep_zip?: string | null;

  // Portal linkage (magic-link client portal)
  portal_activated_at?: string | null;
  portal_onboarded_at?: string | null;

  // Free-form
  additional_contacts?: AdditionalContact[];
  notes?: string | null;
  tags?: string[];

  // ── Billing↔CRM sync mirror (Session 21) ────────────────────────
  // Mirrored from the advertiser's most recent agreement so the CRM
  // detail page can render billing/payment/deal facts without joining
  // agreements. Source of truth is still the agreement row; this is a
  // cache kept in lockstep by lib/server/billing-crm-sync.ts.
  billing_contact_name?: string | null;
  billing_contact_phone?: string | null;
  billing_email?: string | null;
  payment_mode?: string | null;
  stripe_customer_id?: string | null;
  card_last4?: string | null;
  current_agreement_id?: string | null;
  current_ad_size?: string | null;
  current_frequency?: string | null;
  current_ad_rate_cents?: number | null;
  current_amount_cents?: number | null;
  current_exp_date?: string | null;
}

// ── Session 19: Locations + Staff ─────────────────────────────────
export interface AdvertiserLocation {
  id: string;
  advertiser_id: number;
  label: string | null;
  address: string | null;
  address_2: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  phone: string | null;
  email: string | null;
  hours: string | null;
  is_primary: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface AdvertiserStaff {
  id: string;
  advertiser_id: number;
  name: string;
  title: string | null;
  email: string | null;
  phone: string | null;
  photo_url: string | null;
  sort_order: number;
  /** IDs of locations this staff member is assigned to (many-to-many). */
  location_ids: string[];
  created_at: string;
  updated_at: string;
}

export interface AdvertiserWithStats extends Advertiser {
  hotspot_count: number;
  clicks_30d: number;
}

// ── CRM-only stats shape (used by /admin/crm) ─────────────────────
export interface AdvertiserCrmRow extends Advertiser {
  hotspot_count: number;
  clicks_30d: number;
  /** Most recent click timestamp across all of this advertiser's hotspots. */
  last_click_at: string | null;
}

// ── Allow-list of patchable CRM fields ────────────────────────────
// Used by PATCH /api/admin/advertisers/[id] to gate which columns
// clients may write.
export const CRM_PATCHABLE_FIELDS = [
  'type', 'status',
  'first_name', 'last_name', 'company', 'title', 'industry',
  'license_number', 'avatar_url',
  'portal_email', 'phone', 'office_phone', 'website',
  'facebook_url', 'instagram_url', 'linkedin_url', 'twitter_url', 'youtube_url',
  'tagline', 'bio', 'header_style', 'footer_template',
  'email_status', 'email_verified_at',
  'address', 'address_2', 'city', 'state', 'zip',
  'rep_address', 'rep_city', 'rep_state', 'rep_zip',
  'portal_activated_at', 'portal_onboarded_at',
  'additional_contacts', 'notes', 'tags',
] as const;

/** Generate a URL-safe slug from a free-form name. */
export function slugify(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

/** 18-byte (144-bit) url-safe share token. */
export function generateShareToken(): string {
  return randomBytes(18).toString('base64url');
}
