export type TrecFormFieldType = "text" | "checkbox" | "radio" | "choice";

export type TrecFormFieldDefinition = {
  id: string;
  page: number;
  index: number;
  type: TrecFormFieldType;
  label: string;
  pdfFieldName: string;
};

export const TREC_FORM_ID = "20-19" as const;
export const TREC_FORM_EFFECTIVE_DATE = "2026-07-01" as const;
export const TREC_FORM_FIELD_COUNT = 280 as const;

export const TREC_20_19_FIELDS: readonly TrecFormFieldDefinition[] = [
  {
    id: "p01_f001",
    page: 1,
    index: 1,
    type: "text",
    label: "1. PARTIES: The parties to this contract are",
    pdfFieldName: "1 PARTIES The parties to this contract are",
  },
  {
    id: "p01_f002",
    page: 1,
    index: 2,
    type: "text",
    label: "Seller) and",
    pdfFieldName: "Seller and",
  },
  {
    id: "p01_f003",
    page: 1,
    index: 3,
    type: "text",
    label: "A. LAND: Lot",
    pdfFieldName: "A LAND Lot",
  },
  {
    id: "p01_f004",
    page: 1,
    index: 4,
    type: "text",
    label: "Block",
    pdfFieldName: "Block",
  },
  {
    id: "p01_f005",
    page: 1,
    index: 5,
    type: "text",
    label: "Unlabeled field 005",
    pdfFieldName: "undefined",
  },
  {
    id: "p01_f006",
    page: 1,
    index: 6,
    type: "text",
    label: "Addition, City of",
    pdfFieldName: "Addition City of",
  },
  {
    id: "p01_f007",
    page: 1,
    index: 7,
    type: "text",
    label: "County of",
    pdfFieldName: "County of",
  },
  {
    id: "p01_f008",
    page: 1,
    index: 8,
    type: "text",
    label: "Texas, known as",
    pdfFieldName: "Texas known as",
  },
  {
    id: "p01_f009",
    page: 1,
    index: 9,
    type: "text",
    label: "be removed prior to delivery of possession",
    pdfFieldName: "be removed prior to delivery of possession",
  },
  {
    id: "p01_f010",
    page: 1,
    index: 10,
    type: "text",
    label: "Unlabeled field 010",
    pdfFieldName: "undefined_2",
  },
  {
    id: "p01_f011",
    page: 1,
    index: 11,
    type: "text",
    label: "Unlabeled field 011",
    pdfFieldName: "undefined_3",
  },
  {
    id: "p01_f012",
    page: 1,
    index: 12,
    type: "checkbox",
    label: "B. Sum of all financing described in the attached",
    pdfFieldName: "B Sum of all financing described in the attached",
  },
  {
    id: "p01_f013",
    page: 1,
    index: 13,
    type: "checkbox",
    label: "Check Box2",
    pdfFieldName: "Check Box2",
  },
  {
    id: "p01_f014",
    page: 1,
    index: 14,
    type: "checkbox",
    label: "Loan Assumption Addendum",
    pdfFieldName: "Loan Assumption Addendum",
  },
  {
    id: "p01_f015",
    page: 1,
    index: 15,
    type: "text",
    label: "Unlabeled field 015",
    pdfFieldName: "undefined_4",
  },
  {
    id: "p01_f016",
    page: 1,
    index: 16,
    type: "text",
    label: "Unlabeled field 016",
    pdfFieldName: "undefined_5",
  },
  {
    id: "p01_f017",
    page: 1,
    index: 17,
    type: "checkbox",
    label: "i) will not be amended or deleted from the title policy; or",
    pdfFieldName: "i will not be amended or deleted from the title policy or",
  },
  {
    id: "p01_f018",
    page: 1,
    index: 18,
    type: "checkbox",
    label: 'ii) will be amended to read, "shortages in area" at the expense of',
    pdfFieldName:
      "ii will be amended to read shortages in area at the expense of",
  },
  {
    id: "p01_f019",
    page: 1,
    index: 19,
    type: "checkbox",
    label: "A. TITLE POLICY: Seller shall furnish to Buyer at",
    pdfFieldName: "A TITLE POLICY Seller shall furnish to Buyer at",
  },
  {
    id: "p01_f020",
    page: 1,
    index: 20,
    type: "checkbox",
    label: "Seller’s",
    pdfFieldName: "Sellers",
  },
  {
    id: "p01_f021",
    page: 1,
    index: 21,
    type: "checkbox",
    label: "Seller",
    pdfFieldName: "Seller",
  },
  {
    id: "p01_f022",
    page: 1,
    index: 22,
    type: "text",
    label: "to escrow agent within",
    pdfFieldName: "to escrow agent within 1",
  },
  {
    id: "p01_f023",
    page: 1,
    index: 23,
    type: "text",
    label: "Initialed for identification by Buyer",
    pdfFieldName: "Initialed for identification by Buyer",
  },
  {
    id: "p01_f024",
    page: 1,
    index: 24,
    type: "text",
    label: "Unlabeled field 024",
    pdfFieldName: "undefined_8",
  },
  {
    id: "p01_f025",
    page: 1,
    index: 25,
    type: "text",
    label: "and Seller",
    pdfFieldName: "and Seller",
  },
  {
    id: "p01_f026",
    page: 1,
    index: 26,
    type: "text",
    label: "Unlabeled field 026",
    pdfFieldName: "undefined_9",
  },
  {
    id: "p02_f027",
    page: 2,
    index: 27,
    type: "text",
    label: "Page 2 of 10",
    pdfFieldName: "Page 2 of 10",
  },
  {
    id: "p02_f028",
    page: 2,
    index: 28,
    type: "text",
    label: "Unlabeled field 028",
    pdfFieldName: "undefined_6",
  },
  {
    id: "p02_f029",
    page: 2,
    index: 29,
    type: "text",
    label:
      "other party in writing before entering into a contract of sale.  Disclose if applicable",
    pdfFieldName:
      "other party in writing before entering into a contract of sale  Disclose if applicable",
  },
  {
    id: "p02_f030",
    page: 2,
    index: 30,
    type: "text",
    label: "Unlabeled field 030",
    pdfFieldName: "undefined_7",
  },
  {
    id: "p02_f031",
    page: 2,
    index: 31,
    type: "text",
    label: "as earnest money to",
    pdfFieldName: "as earnest money to",
  },
  {
    id: "p02_f032",
    page: 2,
    index: 32,
    type: "text",
    label: "as earnest money to",
    pdfFieldName: "as earnest money to 2",
  },
  {
    id: "p02_f033",
    page: 2,
    index: 33,
    type: "text",
    label: "earnest money of",
    pdfFieldName: "earnest money of",
  },
  {
    id: "p02_f034",
    page: 2,
    index: 34,
    type: "text",
    label: "to escrow agent within",
    pdfFieldName: "to escrow agent within",
  },
  {
    id: "p02_f035",
    page: 2,
    index: 35,
    type: "text",
    label: "the Title Company and Buyer’s lender(s). (Check one box only",
    pdfFieldName: "the Title Company and Buyers lenders Check one box only",
  },
  {
    id: "p02_f036",
    page: 2,
    index: 36,
    type: "checkbox",
    label: "Seller's",
    pdfFieldName: "Sellers_2",
  },
  {
    id: "p02_f037",
    page: 2,
    index: 37,
    type: "checkbox",
    label: "Buyer's expense no later",
    pdfFieldName: "Buyers expense no later",
  },
  {
    id: "p02_f038",
    page: 2,
    index: 38,
    type: "text",
    label: "insurance (Title Policy) issued by",
    pdfFieldName: "insurance Title Policy issued by",
  },
  {
    id: "p02_f039",
    page: 2,
    index: 39,
    type: "checkbox",
    label: "2)Within",
    pdfFieldName: "2Within",
  },
  {
    id: "p02_f040",
    page: 2,
    index: 40,
    type: "checkbox",
    label: "3)Within",
    pdfFieldName: "3Within",
  },
  {
    id: "p02_f041",
    page: 2,
    index: 41,
    type: "checkbox",
    label: "is",
    pdfFieldName: "is",
  },
  {
    id: "p02_f042",
    page: 2,
    index: 42,
    type: "checkbox",
    label: "is not",
    pdfFieldName: "is not",
  },
  {
    id: "p02_f043",
    page: 2,
    index: 43,
    type: "text",
    label: "2) MEMBERSHIP IN PROPERTY OWNERS ASSOCIATION(S): The Property",
    pdfFieldName: "2 MEMBERSHIP IN PROPERTY OWNERS ASSOCIATIONS The Property",
  },
  {
    id: "p02_f044",
    page: 2,
    index: 44,
    type: "text",
    label: "and Seller",
    pdfFieldName: "and Seller_2",
  },
  {
    id: "p02_f045",
    page: 2,
    index: 45,
    type: "text",
    label: "Unlabeled field 045",
    pdfFieldName: "undefined_10",
  },
  {
    id: "p02_f046",
    page: 2,
    index: 46,
    type: "text",
    label: "Unlabeled field 046",
    pdfFieldName: "undefined_11",
  },
  {
    id: "p03_f047",
    page: 3,
    index: 47,
    type: "text",
    label: "Page 3 of 10",
    pdfFieldName: "Page 3 of 10",
  },
  {
    id: "p03_f048",
    page: 3,
    index: 48,
    type: "checkbox",
    label: "Buyer",
    pdfFieldName: "Buyer",
  },
  {
    id: "p03_f049",
    page: 3,
    index: 49,
    type: "text",
    label: "than 3 days prior to Closing Date",
    pdfFieldName: "than 3 days prior to Closing Date",
  },
  {
    id: "p03_f050",
    page: 3,
    index: 50,
    type: "checkbox",
    label: "1)Within",
    pdfFieldName: "Within one",
  },
  {
    id: "p03_f051",
    page: 3,
    index: 51,
    type: "checkbox",
    label: "1)Within",
    pdfFieldName: "Within two",
  },
  {
    id: "p03_f052",
    page: 3,
    index: 52,
    type: "checkbox",
    label: "1)Within",
    pdfFieldName: "Within three",
  },
  {
    id: "p03_f053",
    page: 3,
    index: 53,
    type: "text",
    label: "than 3 days prior to Closing Date",
    pdfFieldName: "3 days prior",
  },
  {
    id: "p03_f054",
    page: 3,
    index: 54,
    type: "checkbox",
    label: "1)Within",
    pdfFieldName: "Within four",
  },
  {
    id: "p03_f055",
    page: 3,
    index: 55,
    type: "text",
    label:
      "receipt or the date specified in this paragraph, whichever is earlier",
    pdfFieldName:
      "receipt or the date specified in this paragraph whichever is earlier",
  },
  {
    id: "p03_f056",
    page: 3,
    index: 56,
    type: "text",
    label:
      "Commitment other than items 6A(1) through (9) above; or which prohibit the following use",
    pdfFieldName:
      "Commitment other than items 6A1 through 9 above or which prohibit the following use",
  },
  {
    id: "p03_f057",
    page: 3,
    index: 57,
    type: "text",
    label:
      "the Commitment, Exception Documents, and the survey. Buyer’s failure to object within the",
    pdfFieldName:
      "the Commitment Exception Documents and the survey Buyers failure to object within the",
  },
  {
    id: "p03_f058",
    page: 3,
    index: 58,
    type: "checkbox",
    label: "1)Within",
    pdfFieldName: "1Within",
  },
  {
    id: "p03_f059",
    page: 3,
    index: 59,
    type: "checkbox",
    label: "1)Within",
    pdfFieldName: "2 Within",
  },
  {
    id: "p03_f060",
    page: 3,
    index: 60,
    type: "text",
    label: "Property Code, requires Seller to notify Buyer as follows",
    pdfFieldName: "Property Code requires Seller to notify Buyer as follows",
  },
  {
    id: "p03_f061",
    page: 3,
    index: 61,
    type: "text",
    label: "and Seller",
    pdfFieldName: "and Seller_3",
  },
  {
    id: "p03_f062",
    page: 3,
    index: 62,
    type: "text",
    label: "Unlabeled field 062",
    pdfFieldName: "undefined_12",
  },
  {
    id: "p03_f063",
    page: 3,
    index: 63,
    type: "text",
    label: "The private transfer fee",
    pdfFieldName: "The private transfer fee",
  },
  {
    id: "p04_f064",
    page: 4,
    index: 64,
    type: "text",
    label: "Contract Concerning",
    pdfFieldName: "Contract Concerning",
  },
  {
    id: "p04_f065",
    page: 4,
    index: 65,
    type: "checkbox",
    label: "1) Buyer accepts the Property As Is",
    pdfFieldName: "1 Buyer accepts the Property As Is",
  },
  {
    id: "p04_f066",
    page: 4,
    index: 66,
    type: "checkbox",
    label:
      "2) Buyer accepts the Property As Is provided Seller, at Seller’s expense, shall complete the",
    pdfFieldName:
      "2 Buyer accepts the Property As Is provided Seller at Sellers expense shall complete the",
  },
  {
    id: "p04_f067",
    page: 4,
    index: 67,
    type: "text",
    label: "Within",
    pdfFieldName: "Within",
  },
  {
    id: "p04_f068",
    page: 4,
    index: 68,
    type: "checkbox",
    label: "upon",
    pdfFieldName: "upon",
  },
  {
    id: "p04_f069",
    page: 4,
    index: 69,
    type: "text",
    label: "Initialed for identification by Buyer",
    pdfFieldName: "Initialed for identification by Buyer_2",
  },
  {
    id: "p04_f070",
    page: 4,
    index: 70,
    type: "text",
    label: "Unlabeled field 070",
    pdfFieldName: "undefined_14",
  },
  {
    id: "p04_f071",
    page: 4,
    index: 71,
    type: "text",
    label: "and Seller",
    pdfFieldName: "and Seller_4",
  },
  {
    id: "p04_f072",
    page: 4,
    index: 72,
    type: "text",
    label: "Unlabeled field 072",
    pdfFieldName: "undefined_15",
  },
  {
    id: "p05_f073",
    page: 5,
    index: 73,
    type: "text",
    label: "Contract Concerning",
    pdfFieldName: "Contract Concerning_2",
  },
  {
    id: "p05_f074",
    page: 5,
    index: 74,
    type: "checkbox",
    label:
      "according to a temporary residential lease form promulgated by TREC or other written",
    pdfFieldName: "As Is",
  },
  {
    id: "p05_f075",
    page: 5,
    index: 75,
    type: "checkbox",
    label:
      "according to a temporary residential lease form promulgated by TREC or other written",
    pdfFieldName: "As Is except",
  },
  {
    id: "p05_f076",
    page: 5,
    index: 76,
    type: "text",
    label: "following specific repairs and treatments",
    pdfFieldName: "following specific repairs and treatments",
  },
  {
    id: "p05_f077",
    page: 5,
    index: 77,
    type: "text",
    label: "Unlabeled field 077",
    pdfFieldName: "undefined_13",
  },
  {
    id: "p05_f078",
    page: 5,
    index: 78,
    type: "text",
    label: "service contract in an amount not exceeding",
    pdfFieldName: "service contract in an amount not exceeding0",
  },
  {
    id: "p05_f079",
    page: 5,
    index: 79,
    type: "checkbox",
    label: "Seller as Listing Broker’s subagent",
    pdfFieldName: "Seller as List Brok Sub agent2",
  },
  {
    id: "p05_f080",
    page: 5,
    index: 80,
    type: "checkbox",
    label: "Seller and Buyer as an intermediary",
    pdfFieldName: "Dollar Amt2",
  },
  {
    id: "p05_f081",
    page: 5,
    index: 81,
    type: "text",
    label: "service contract in an amount not exceeding",
    pdfFieldName: "service contract in an amount not exceeding1",
  },
  {
    id: "p05_f082",
    page: 5,
    index: 82,
    type: "checkbox",
    label: "Dollar Amt",
    pdfFieldName: "Dollar Amt",
  },
  {
    id: "p05_f083",
    page: 5,
    index: 83,
    type: "text",
    label: "service contract in an amount not exceeding",
    pdfFieldName: "service contract in an amount not exceeding3",
  },
  {
    id: "p05_f084",
    page: 5,
    index: 84,
    type: "text",
    label: "service contract in an amount not exceeding",
    pdfFieldName: "service contract in an amount not exceeding",
  },
  {
    id: "p05_f085",
    page: 5,
    index: 85,
    type: "text",
    label: "Initialed for identification by Buyer",
    pdfFieldName: "Initialed for identification by Buyer_3",
  },
  {
    id: "p05_f086",
    page: 5,
    index: 86,
    type: "text",
    label: "Buyer’s Expenses as allowed by the lender",
    pdfFieldName: "Buyers Expenses as allowed by the lender",
  },
  {
    id: "p05_f087",
    page: 5,
    index: 87,
    type: "text",
    label: "and Seller",
    pdfFieldName: "and Seller_5",
  },
  {
    id: "p05_f088",
    page: 5,
    index: 88,
    type: "text",
    label: "Unlabeled field 088",
    pdfFieldName: "undefined_16",
  },
  {
    id: "p06_f089",
    page: 6,
    index: 89,
    type: "text",
    label: "Contract Concerning",
    pdfFieldName: "Contract Concerning_3",
  },
  {
    id: "p06_f090",
    page: 6,
    index: 90,
    type: "text",
    label: "b) Seller shall also pay an amount not to exceed",
    pdfFieldName: "Brokers and Sales4",
  },
  {
    id: "p06_f091",
    page: 6,
    index: 91,
    type: "text",
    label: "Brokers and Sales",
    pdfFieldName: "Brokers and Sales",
  },
  {
    id: "p06_f092",
    page: 6,
    index: 92,
    type: "text",
    label: "Brokers and Sales 2",
    pdfFieldName: "Brokers and Sales 2",
  },
  {
    id: "p06_f093",
    page: 6,
    index: 93,
    type: "text",
    label: "A The closing of the sale will be on or before",
    pdfFieldName: "A The closing of the sale will be on or before",
  },
  {
    id: "p06_f094",
    page: 6,
    index: 94,
    type: "text",
    label: "20",
    pdfFieldName: "20",
  },
  {
    id: "p06_f095",
    page: 6,
    index: 95,
    type: "checkbox",
    label: "will",
    pdfFieldName: "will",
  },
  {
    id: "p06_f096",
    page: 6,
    index: 96,
    type: "checkbox",
    label: "will not be credited to the Sales Price at closing. Time is of the",
    pdfFieldName:
      "will not be credited to the Sales Price at closing Time is of the",
  },
  {
    id: "p06_f097",
    page: 6,
    index: 97,
    type: "text",
    label: "Text3",
    pdfFieldName: "Text3",
  },
  {
    id: "p06_f098",
    page: 6,
    index: 98,
    type: "text",
    label: "Text3 2",
    pdfFieldName: "Text3 2",
  },
  {
    id: "p06_f099",
    page: 6,
    index: 99,
    type: "text",
    label: "Text3 3",
    pdfFieldName: "Text3 3",
  },
  {
    id: "p06_f100",
    page: 6,
    index: 100,
    type: "text",
    label: "acknowledged by Seller and Buyers agreement to pay Seller 1",
    pdfFieldName: "acknowledged by Seller and Buyers agreement to pay Seller 1",
  },
  {
    id: "p06_f101",
    page: 6,
    index: 101,
    type: "text",
    label: "Initialed for identification by Buyer",
    pdfFieldName: "Initialed for identification by Buyer_4",
  },
  {
    id: "p06_f102",
    page: 6,
    index: 102,
    type: "text",
    label: "Unlabeled field 102",
    pdfFieldName: "undefined_17",
  },
  {
    id: "p06_f103",
    page: 6,
    index: 103,
    type: "text",
    label: "and Seller",
    pdfFieldName: "and Seller_6",
  },
  {
    id: "p06_f104",
    page: 6,
    index: 104,
    type: "text",
    label: "Unlabeled field 104",
    pdfFieldName: "undefined_18",
  },
  {
    id: "p07_f105",
    page: 7,
    index: 105,
    type: "text",
    label: "Page 7 of 10",
    pdfFieldName: "Page 7 of 10",
  },
  {
    id: "p07_f106",
    page: 7,
    index: 106,
    type: "checkbox",
    label: "Seller as List Brok Sub agent",
    pdfFieldName: "Seller as List Brok Sub agent",
  },
  {
    id: "p07_f107",
    page: 7,
    index: 107,
    type: "checkbox",
    label: "Seller as Listing Broker’s subagent",
    pdfFieldName: "Seller as List Brok Sub agent27",
  },
  {
    id: "p07_f108",
    page: 7,
    index: 108,
    type: "text",
    label: "acknowledged by Seller, and Buyer's agreement to pay Seller",
    pdfFieldName:
      "acknowledged by Seller and Buyers agreement to pay Seller 130",
  },
  {
    id: "p07_f109",
    page: 7,
    index: 109,
    type: "checkbox",
    label: "Seller only as Seller’s agent",
    pdfFieldName: "Seller only as Sellers agent",
  },
  {
    id: "p07_f110",
    page: 7,
    index: 110,
    type: "text",
    label: "acknowledged by Seller, and Buyer's agreement to pay Seller",
    pdfFieldName:
      "acknowledged by Seller and Buyers agreement to pay Seller 31",
  },
  {
    id: "p07_f111",
    page: 7,
    index: 111,
    type: "checkbox",
    label: "Seller and Buyer as an intermediary",
    pdfFieldName: "Dollar Amt4",
  },
  {
    id: "p07_f112",
    page: 7,
    index: 112,
    type: "checkbox",
    label: "Seller and Buyer as an intermediary",
    pdfFieldName: "Dollar Amt5",
  },
  {
    id: "p07_f113",
    page: 7,
    index: 113,
    type: "text",
    label: "acknowledged by Seller and Buyers agreement to pay Seller 32",
    pdfFieldName:
      "acknowledged by Seller and Buyers agreement to pay Seller 32",
  },
  {
    id: "p07_f114",
    page: 7,
    index: 114,
    type: "checkbox",
    label: "Seller only as Seller’s agent",
    pdfFieldName: "Percentage",
  },
  {
    id: "p07_f115",
    page: 7,
    index: 115,
    type: "text",
    label: "acknowledged by Seller, and Buyer's agreement to pay Seller",
    pdfFieldName:
      "acknowledged by Seller and Buyers agreement to pay Seller 40",
  },
  {
    id: "p07_f116",
    page: 7,
    index: 116,
    type: "text",
    label: "AC numb 1",
    pdfFieldName: "AC numb 1",
  },
  {
    id: "p07_f117",
    page: 7,
    index: 117,
    type: "text",
    label: "AC numb 2",
    pdfFieldName: "AC numb 2",
  },
  {
    id: "p07_f118",
    page: 7,
    index: 118,
    type: "text",
    label: "AC numb 3",
    pdfFieldName: "AC numb 3",
  },
  {
    id: "p07_f119",
    page: 7,
    index: 119,
    type: "text",
    label: "AC numb 4",
    pdfFieldName: "AC numb 4",
  },
  {
    id: "p08_f120",
    page: 8,
    index: 120,
    type: "text",
    label: "Contract Concerning",
    pdfFieldName: "Contract Concerning_4",
  },
  {
    id: "p08_f121",
    page: 8,
    index: 121,
    type: "text",
    label:
      "when mailed to, hand-delivered at, or transmitted by fax or electronic transmission as follows",
    pdfFieldName:
      "when mailed to handdelivered at or transmitted by fax or electronic transmission as follow15",
  },
  {
    id: "p08_f122",
    page: 8,
    index: 122,
    type: "text",
    label: "at",
    pdfFieldName: "at7",
  },
  {
    id: "p08_f123",
    page: 8,
    index: 123,
    type: "text",
    label: "Phone 5217",
    pdfFieldName: "Phone 5217",
  },
  {
    id: "p08_f124",
    page: 8,
    index: 124,
    type: "text",
    label: "Unlabeled field 124",
    pdfFieldName: "undefined_20-011",
  },
  {
    id: "p08_f125",
    page: 8,
    index: 125,
    type: "text",
    label: "Unlabeled field 125",
    pdfFieldName: "undefined_2013",
  },
  {
    id: "p08_f126",
    page: 8,
    index: 126,
    type: "text",
    label: "Unlabeled field 126",
    pdfFieldName: "undefined_20-0",
  },
  {
    id: "p08_f127",
    page: 8,
    index: 127,
    type: "text",
    label: "Unlabeled field 127",
    pdfFieldName: "undefined6",
  },
  {
    id: "p08_f128",
    page: 8,
    index: 128,
    type: "text",
    label: "at",
    pdfFieldName: "at_28",
  },
  {
    id: "p08_f129",
    page: 8,
    index: 129,
    type: "text",
    label: "Unlabeled field 129",
    pdfFieldName: "undefined numb 2110",
  },
  {
    id: "p08_f130",
    page: 8,
    index: 130,
    type: "text",
    label: "Unlabeled field 130",
    pdfFieldName: "undefined numb 22-012",
  },
  {
    id: "p08_f131",
    page: 8,
    index: 131,
    type: "text",
    label: "Unlabeled field 131",
    pdfFieldName: "undefined numb 2214",
  },
  {
    id: "p08_f132",
    page: 8,
    index: 132,
    type: "text",
    label: "Unlabeled field 132",
    pdfFieldName: "undefined numb 22-0",
  },
  {
    id: "p08_f133",
    page: 8,
    index: 133,
    type: "text",
    label:
      "when mailed to handdelivered at or transmitted by fax or electronic transmission as follows",
    pdfFieldName:
      "when mailed to handdelivered at or transmitted by fax or electronic transmission as follows",
  },
  {
    id: "p08_f134",
    page: 8,
    index: 134,
    type: "text",
    label: "at",
    pdfFieldName: "at",
  },
  {
    id: "p08_f135",
    page: 8,
    index: 135,
    type: "text",
    label: "Phone 52",
    pdfFieldName: "Phone 52",
  },
  {
    id: "p08_f136",
    page: 8,
    index: 136,
    type: "text",
    label: "Unlabeled field 136",
    pdfFieldName: "undefined_20",
  },
  {
    id: "p08_f137",
    page: 8,
    index: 137,
    type: "text",
    label: "Unlabeled field 137",
    pdfFieldName: "undefined_19",
  },
  {
    id: "p08_f138",
    page: 8,
    index: 138,
    type: "text",
    label: "at_2",
    pdfFieldName: "at_2",
  },
  {
    id: "p08_f139",
    page: 8,
    index: 139,
    type: "text",
    label: "Unlabeled field 139",
    pdfFieldName: "undefined numb 21",
  },
  {
    id: "p08_f140",
    page: 8,
    index: 140,
    type: "text",
    label: "Unlabeled field 140",
    pdfFieldName: "undefined numb 22",
  },
  {
    id: "p08_f141",
    page: 8,
    index: 141,
    type: "text",
    label: "Initialed for identification by Buyer",
    pdfFieldName: "Initialed for identification by Buyer_521",
  },
  {
    id: "p08_f142",
    page: 8,
    index: 142,
    type: "text",
    label: "and Seller",
    pdfFieldName: "and Seller_18",
  },
  {
    id: "p08_f143",
    page: 8,
    index: 143,
    type: "text",
    label: "Unlabeled field 143",
    pdfFieldName: "undefined_2219",
  },
  {
    id: "p08_f144",
    page: 8,
    index: 144,
    type: "text",
    label: "Unlabeled field 144",
    pdfFieldName: "undefined_2322",
  },
  {
    id: "p09_f145",
    page: 9,
    index: 145,
    type: "text",
    label: "Address of Property",
    pdfFieldName: "Address of Property",
  },
  {
    id: "p09_f146",
    page: 9,
    index: 146,
    type: "checkbox",
    label: "Addendum for Reservation of Oil, Gas",
    pdfFieldName: "Addendum for Reservation of Oil Gas",
  },
  {
    id: "p09_f147",
    page: 9,
    index: 147,
    type: "checkbox",
    label: "Addendum for Seller's Disclosure of",
    pdfFieldName: "Sellers Disclos",
  },
  {
    id: "p09_f148",
    page: 9,
    index: 148,
    type: "checkbox",
    label: 'Addendum for "Back-Up" Contract',
    pdfFieldName: "Addendum for BackUp Contract",
  },
  {
    id: "p09_f149",
    page: 9,
    index: 149,
    type: "checkbox",
    label: "Addendum for Seller's Disclosure of",
    pdfFieldName: "Addend. for Sellers Disclos",
  },
  {
    id: "p09_f150",
    page: 9,
    index: 150,
    type: "checkbox",
    label: "Other (list",
    pdfFieldName: "Other",
  },
  {
    id: "p09_f151",
    page: 9,
    index: 151,
    type: "checkbox",
    label: "Addendum Concerning Right to",
    pdfFieldName: "Check box 11",
  },
  {
    id: "p09_f152",
    page: 9,
    index: 152,
    type: "checkbox",
    label: "Environmental Assessment, Threatened or",
    pdfFieldName: "Environmental Assessment Threatened or",
  },
  {
    id: "p09_f153",
    page: 9,
    index: 153,
    type: "checkbox",
    label: "Third Party Financing Addendum",
    pdfFieldName: "Third Party Financing Addendum",
  },
  {
    id: "p09_f154",
    page: 9,
    index: 154,
    type: "checkbox",
    label: "Seller’s Temporary Residential Lease",
    pdfFieldName: "Sellers Temporary Residential Lease",
  },
  {
    id: "p09_f155",
    page: 9,
    index: 155,
    type: "checkbox",
    label: "Seller Financing Addendum",
    pdfFieldName: "Seller Financing Addendum",
  },
  {
    id: "p09_f156",
    page: 9,
    index: 156,
    type: "checkbox",
    label: "Short Sale Addendum",
    pdfFieldName: "Short Sale Addendum",
  },
  {
    id: "p09_f157",
    page: 9,
    index: 157,
    type: "checkbox",
    label: "Addendum for Property Subject to",
    pdfFieldName: "Addendum for Property Subject to",
  },
  {
    id: "p09_f158",
    page: 9,
    index: 158,
    type: "checkbox",
    label: "Addendum for Property Located Seaward",
    pdfFieldName: "Addendum for Property Located Seaward",
  },
  {
    id: "p09_f159",
    page: 9,
    index: 159,
    type: "checkbox",
    label: "Buyer’s Temporary Residential Lease",
    pdfFieldName: "Buyers Temporary Residential Lease",
  },
  {
    id: "p09_f160",
    page: 9,
    index: 160,
    type: "checkbox",
    label: "Loan Assumption Addendum",
    pdfFieldName: "Loan Assumption Addendum_2",
  },
  {
    id: "p09_f161",
    page: 9,
    index: 161,
    type: "checkbox",
    label: "Addendum for Sale of Other Property by",
    pdfFieldName: "Addendum for Sale of Other Property by",
  },
  {
    id: "p09_f162",
    page: 9,
    index: 162,
    type: "checkbox",
    label: "Addendum for Property in a Propane Gas",
    pdfFieldName: "Addendum for Property in a Propane Gas",
  },
  {
    id: "p09_f163",
    page: 9,
    index: 163,
    type: "checkbox",
    label: "Check Box8",
    pdfFieldName: "Check Box8",
  },
  {
    id: "p09_f164",
    page: 9,
    index: 164,
    type: "checkbox",
    label: "Other (list",
    pdfFieldName: "PID",
  },
  {
    id: "p09_f165",
    page: 9,
    index: 165,
    type: "text",
    label: "b) Seller shall also pay an amount not to exceed",
    pdfFieldName: "Brokers and Sales20",
  },
  {
    id: "p09_f166",
    page: 9,
    index: 166,
    type: "text",
    label: "b) Seller shall also pay an amount not to exceed",
    pdfFieldName: "Brokers and Sales21",
  },
  {
    id: "p09_f167",
    page: 9,
    index: 167,
    type: "checkbox",
    label: "Check Box9",
    pdfFieldName: "Check Box9",
  },
  {
    id: "p09_f168",
    page: 9,
    index: 168,
    type: "checkbox",
    label: "Other (list",
    pdfFieldName: "Addendum for Section 1031",
  },
  {
    id: "p09_f169",
    page: 9,
    index: 169,
    type: "checkbox",
    label: "Addendum Concerning Right to",
    pdfFieldName: "Check box 10",
  },
  {
    id: "p09_f170",
    page: 9,
    index: 170,
    type: "checkbox",
    label: "Buyer only as Buyer’s agent",
    pdfFieldName: "Buyer only",
  },
  {
    id: "p09_f171",
    page: 9,
    index: 171,
    type: "checkbox",
    label: "Seller and Buyer as an intermediary",
    pdfFieldName: "Seller and Buyer as an intermediary",
  },
  {
    id: "p09_f172",
    page: 9,
    index: 172,
    type: "text",
    label: "b) Seller shall also pay an amount not to exceed",
    pdfFieldName: "Brokers and Sales22",
  },
  {
    id: "p09_f173",
    page: 9,
    index: 173,
    type: "text",
    label: "b) Seller shall also pay an amount not to exceed",
    pdfFieldName: "Brokers and Sales41",
  },
  {
    id: "p09_f174",
    page: 9,
    index: 174,
    type: "text",
    label: "Attorney is",
    pdfFieldName: "Attorney is",
  },
  {
    id: "p09_f175",
    page: 9,
    index: 175,
    type: "text",
    label: "Unlabeled field 175",
    pdfFieldName: "undefined_24",
  },
  {
    id: "p09_f176",
    page: 9,
    index: 176,
    type: "text",
    label: "Text2",
    pdfFieldName: "Text2",
  },
  {
    id: "p09_f177",
    page: 9,
    index: 177,
    type: "text",
    label: "Text1",
    pdfFieldName: "Text1",
  },
  {
    id: "p09_f178",
    page: 9,
    index: 178,
    type: "text",
    label: "Text7",
    pdfFieldName: "Text7",
  },
  {
    id: "p09_f179",
    page: 9,
    index: 179,
    type: "text",
    label: "Text6",
    pdfFieldName: "Text6",
  },
  {
    id: "p09_f180",
    page: 9,
    index: 180,
    type: "text",
    label: "E-mail",
    pdfFieldName: "Email",
  },
  {
    id: "p09_f181",
    page: 9,
    index: 181,
    type: "text",
    label: "Attorney is",
    pdfFieldName: "Attorney is_2",
  },
  {
    id: "p09_f182",
    page: 9,
    index: 182,
    type: "text",
    label: "Unlabeled field 182",
    pdfFieldName: "undefined_25",
  },
  {
    id: "p09_f183",
    page: 9,
    index: 183,
    type: "text",
    label: "Text22",
    pdfFieldName: "Text22",
  },
  {
    id: "p09_f184",
    page: 9,
    index: 184,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone11",
  },
  {
    id: "p09_f185",
    page: 9,
    index: 185,
    type: "text",
    label: "Text23",
    pdfFieldName: "Text23",
  },
  {
    id: "p09_f186",
    page: 9,
    index: 186,
    type: "text",
    label: "Phone 2",
    pdfFieldName: "Phone 2",
  },
  {
    id: "p09_f187",
    page: 9,
    index: 187,
    type: "text",
    label: "E-mail",
    pdfFieldName: "Email_2",
  },
  {
    id: "p09_f188",
    page: 9,
    index: 188,
    type: "text",
    label: "Initialed for identification by Buyer_5",
    pdfFieldName: "Initialed for identification by Buyer_5",
  },
  {
    id: "p09_f189",
    page: 9,
    index: 189,
    type: "text",
    label: "and Seller_7",
    pdfFieldName: "and Seller_7",
  },
  {
    id: "p09_f190",
    page: 9,
    index: 190,
    type: "text",
    label: "Unlabeled field 190",
    pdfFieldName: "undefined_22",
  },
  {
    id: "p09_f191",
    page: 9,
    index: 191,
    type: "text",
    label: "Unlabeled field 191",
    pdfFieldName: "undefined_23",
  },
  {
    id: "p10_f192",
    page: 10,
    index: 192,
    type: "text",
    label: "Address of Property",
    pdfFieldName: "Addr of Prop",
  },
  {
    id: "p10_f193",
    page: 10,
    index: 193,
    type: "text",
    label: "EXECUTED the",
    pdfFieldName: "EXECUTED the",
  },
  {
    id: "p10_f194",
    page: 10,
    index: 194,
    type: "text",
    label: "day of",
    pdfFieldName: "day of",
  },
  {
    id: "p10_f195",
    page: 10,
    index: 195,
    type: "text",
    label: "20",
    pdfFieldName: "20_2",
  },
  {
    id: "p10_f196",
    page: 10,
    index: 196,
    type: "text",
    label: "Signature8",
    pdfFieldName: "Signature8",
  },
  {
    id: "p10_f197",
    page: 10,
    index: 197,
    type: "text",
    label: "Signature9",
    pdfFieldName: "Signature9",
  },
  {
    id: "p10_f198",
    page: 10,
    index: 198,
    type: "text",
    label: "Signature10",
    pdfFieldName: "Signature10",
  },
  {
    id: "p10_f199",
    page: 10,
    index: 199,
    type: "text",
    label: "Signature11",
    pdfFieldName: "Signature11",
  },
  {
    id: "p11_f200",
    page: 11,
    index: 200,
    type: "text",
    label: "Address of Property_2",
    pdfFieldName: "Address of Property_2",
  },
  {
    id: "p11_f201",
    page: 11,
    index: 201,
    type: "text",
    label: "Other Broker Firm",
    pdfFieldName: "Other Broker Firm",
  },
  {
    id: "p11_f202",
    page: 11,
    index: 202,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No",
  },
  {
    id: "p11_f203",
    page: 11,
    index: 203,
    type: "text",
    label: "Listing Broker Firm",
    pdfFieldName: "Listing Broker Firm",
  },
  {
    id: "p11_f204",
    page: 11,
    index: 204,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No_4",
  },
  {
    id: "p11_f205",
    page: 11,
    index: 205,
    type: "text",
    label: "Associate’s Name",
    pdfFieldName: "Associates Name numb 1",
  },
  {
    id: "p11_f206",
    page: 11,
    index: 206,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No_2",
  },
  {
    id: "p11_f207",
    page: 11,
    index: 207,
    type: "text",
    label: "Listing Associate’s Name",
    pdfFieldName: "List Assoc Name",
  },
  {
    id: "p11_f208",
    page: 11,
    index: 208,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No_5",
  },
  {
    id: "p11_f209",
    page: 11,
    index: 209,
    type: "text",
    label: "Associate’s Name",
    pdfFieldName: "Associates Name",
  },
  {
    id: "p11_f210",
    page: 11,
    index: 210,
    type: "text",
    label: "Listing Associate’s Name",
    pdfFieldName: "Listing Associates Name",
  },
  {
    id: "p11_f211",
    page: 11,
    index: 211,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone_3",
  },
  {
    id: "p11_f212",
    page: 11,
    index: 212,
    type: "text",
    label: "Associate’s Email Address",
    pdfFieldName: "Associates Email Address",
  },
  {
    id: "p11_f213",
    page: 11,
    index: 213,
    type: "text",
    label: "Listing Associate’s Email Address",
    pdfFieldName: "Listing Associates Email Address",
  },
  {
    id: "p11_f214",
    page: 11,
    index: 214,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone",
  },
  {
    id: "p11_f215",
    page: 11,
    index: 215,
    type: "text",
    label: "Licensed Supervisor of Associate",
    pdfFieldName: "Licensed Supervisor of Associate",
  },
  {
    id: "p11_f216",
    page: 11,
    index: 216,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No_3",
  },
  {
    id: "p11_f217",
    page: 11,
    index: 217,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No_6",
  },
  {
    id: "p11_f218",
    page: 11,
    index: 218,
    type: "text",
    label: "Other Broker's Address",
    pdfFieldName: "Other Brokers Address",
  },
  {
    id: "p11_f219",
    page: 11,
    index: 219,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone_2",
  },
  {
    id: "p11_f220",
    page: 11,
    index: 220,
    type: "text",
    label: "Licensed Supervisor of Listing Associate",
    pdfFieldName: "Licensed Supervisor of Listing Associate",
  },
  {
    id: "p11_f221",
    page: 11,
    index: 221,
    type: "text",
    label: "City",
    pdfFieldName: "City",
  },
  {
    id: "p11_f222",
    page: 11,
    index: 222,
    type: "text",
    label: "State",
    pdfFieldName: "State",
  },
  {
    id: "p11_f223",
    page: 11,
    index: 223,
    type: "text",
    label: "Zip",
    pdfFieldName: "Zip",
  },
  {
    id: "p11_f224",
    page: 11,
    index: 224,
    type: "text",
    label: "Listing Broker’s Office Address",
    pdfFieldName: "Listing Brokers Office Address",
  },
  {
    id: "p11_f225",
    page: 11,
    index: 225,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone_4",
  },
  {
    id: "p11_f226",
    page: 11,
    index: 226,
    type: "text",
    label: "City",
    pdfFieldName: "City_2",
  },
  {
    id: "p11_f227",
    page: 11,
    index: 227,
    type: "text",
    label: "State",
    pdfFieldName: "State_2",
  },
  {
    id: "p11_f228",
    page: 11,
    index: 228,
    type: "text",
    label: "Zip",
    pdfFieldName: "Zip_2",
  },
  {
    id: "p11_f229",
    page: 11,
    index: 229,
    type: "text",
    label: "Selling Associate’s Name",
    pdfFieldName: "Selling Associates Name",
  },
  {
    id: "p11_f230",
    page: 11,
    index: 230,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No_7",
  },
  {
    id: "p11_f231",
    page: 11,
    index: 231,
    type: "text",
    label: "Selling Associate’s Name",
    pdfFieldName: "Selling Associates Name-1",
  },
  {
    id: "p11_f232",
    page: 11,
    index: 232,
    type: "text",
    label: "Selling Associate’s Email Address",
    pdfFieldName: "Selling Associates Email Address",
  },
  {
    id: "p11_f233",
    page: 11,
    index: 233,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone_5",
  },
  {
    id: "p11_f234",
    page: 11,
    index: 234,
    type: "text",
    label: "Licensed Supervisor of Selling Associate",
    pdfFieldName: "Licensed Supervisor of Selling Associate",
  },
  {
    id: "p11_f235",
    page: 11,
    index: 235,
    type: "text",
    label: "License No.",
    pdfFieldName: "License No_8",
  },
  {
    id: "p11_f236",
    page: 11,
    index: 236,
    type: "text",
    label: "Selling Associate’s Office Address",
    pdfFieldName: "Selling Associates Office Address",
  },
  {
    id: "p11_f237",
    page: 11,
    index: 237,
    type: "text",
    label:
      "when mailed to, hand-delivered at, or transmitted by fax or electronic transmission as follows",
    pdfFieldName: "when mailed to",
  },
  {
    id: "p11_f238",
    page: 11,
    index: 238,
    type: "text",
    label:
      "when the Listing Broker’s fee is received. Escrow agent is authorized and directed to pay Other Broker from",
    pdfFieldName:
      "when the Listing Brokers fee is received Escrow agent is authorized and directed to pay Other Broker from",
  },
  {
    id: "p11_f239",
    page: 11,
    index: 239,
    type: "text",
    label: "City",
    pdfFieldName: "City_3",
  },
  {
    id: "p11_f240",
    page: 11,
    index: 240,
    type: "text",
    label: "State",
    pdfFieldName: "State_3",
  },
  {
    id: "p11_f241",
    page: 11,
    index: 241,
    type: "text",
    label: "Zip",
    pdfFieldName: "Zip_3",
  },
  {
    id: "p12_f242",
    page: 12,
    index: 242,
    type: "text",
    label: "Address of Property",
    pdfFieldName: "Address of Property_26",
  },
  {
    id: "p12_f243",
    page: 12,
    index: 243,
    type: "text",
    label: "is acknowledged",
    pdfFieldName: "is acknowledged",
  },
  {
    id: "p12_f244",
    page: 12,
    index: 244,
    type: "text",
    label: "Option Fee) in the form of",
    pdfFieldName: "Option Fee in the form of",
  },
  {
    id: "p12_f245",
    page: 12,
    index: 245,
    type: "text",
    label: "Seller or Listing Broker",
    pdfFieldName: "Seller or Listing Broker",
  },
  {
    id: "p12_f246",
    page: 12,
    index: 246,
    type: "text",
    label: "Date",
    pdfFieldName: "Date",
  },
  {
    id: "p12_f247",
    page: 12,
    index: 247,
    type: "text",
    label: "is acknowledged",
    pdfFieldName: "is acknowledged_2",
  },
  {
    id: "p12_f248",
    page: 12,
    index: 248,
    type: "text",
    label: "Earnest Money in the form of",
    pdfFieldName: "Earnest Money in the form of",
  },
  {
    id: "p12_f249",
    page: 12,
    index: 249,
    type: "text",
    label: "Escrow Agent",
    pdfFieldName: "Escrow Agent",
  },
  {
    id: "p12_f250",
    page: 12,
    index: 250,
    type: "text",
    label: "Received by",
    pdfFieldName: "Received by",
  },
  {
    id: "p12_f251",
    page: 12,
    index: 251,
    type: "text",
    label: "Email Address",
    pdfFieldName: "Email Address",
  },
  {
    id: "p12_f252",
    page: 12,
    index: 252,
    type: "text",
    label: "Date/Time",
    pdfFieldName: "DateTime",
  },
  {
    id: "p12_f253",
    page: 12,
    index: 253,
    type: "text",
    label: "Address",
    pdfFieldName: "Address",
  },
  {
    id: "p12_f254",
    page: 12,
    index: 254,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone_6",
  },
  {
    id: "p12_f255",
    page: 12,
    index: 255,
    type: "text",
    label: "City",
    pdfFieldName: "City_4",
  },
  {
    id: "p12_f256",
    page: 12,
    index: 256,
    type: "text",
    label: "State",
    pdfFieldName: "State_4",
  },
  {
    id: "p12_f257",
    page: 12,
    index: 257,
    type: "text",
    label: "Zip",
    pdfFieldName: "Zip_4",
  },
  {
    id: "p12_f258",
    page: 12,
    index: 258,
    type: "text",
    label: "Fax",
    pdfFieldName: "Fax",
  },
  {
    id: "p12_f259",
    page: 12,
    index: 259,
    type: "text",
    label: "Escrow Agent",
    pdfFieldName: "Escrow Agent_2",
  },
  {
    id: "p12_f260",
    page: 12,
    index: 260,
    type: "text",
    label: "Received by",
    pdfFieldName: "Received by_2",
  },
  {
    id: "p12_f261",
    page: 12,
    index: 261,
    type: "text",
    label: "Email Address",
    pdfFieldName: "Email Address_2",
  },
  {
    id: "p12_f262",
    page: 12,
    index: 262,
    type: "text",
    label: "Date",
    pdfFieldName: "Date_2",
  },
  {
    id: "p12_f263",
    page: 12,
    index: 263,
    type: "text",
    label: "Address",
    pdfFieldName: "Address_2",
  },
  {
    id: "p12_f264",
    page: 12,
    index: 264,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone_7",
  },
  {
    id: "p12_f265",
    page: 12,
    index: 265,
    type: "text",
    label: "City",
    pdfFieldName: "City_5",
  },
  {
    id: "p12_f266",
    page: 12,
    index: 266,
    type: "text",
    label: "State",
    pdfFieldName: "State_5",
  },
  {
    id: "p12_f267",
    page: 12,
    index: 267,
    type: "text",
    label: "Zip",
    pdfFieldName: "Zip_5",
  },
  {
    id: "p12_f268",
    page: 12,
    index: 268,
    type: "text",
    label: "Fax",
    pdfFieldName: "Fax_2",
  },
  {
    id: "p12_f269",
    page: 12,
    index: 269,
    type: "text",
    label: "is acknowledged",
    pdfFieldName: "is acknowledged_3",
  },
  {
    id: "p12_f270",
    page: 12,
    index: 270,
    type: "text",
    label: "additional Earnest Money in the form of",
    pdfFieldName: "additional Earnest Money in the form of",
  },
  {
    id: "p12_f271",
    page: 12,
    index: 271,
    type: "text",
    label: "Escrow Agent",
    pdfFieldName: "Escrow Agent_3",
  },
  {
    id: "p12_f272",
    page: 12,
    index: 272,
    type: "text",
    label: "Received by",
    pdfFieldName: "Received by_3",
  },
  {
    id: "p12_f273",
    page: 12,
    index: 273,
    type: "text",
    label: "Email Address",
    pdfFieldName: "Email Address_3",
  },
  {
    id: "p12_f274",
    page: 12,
    index: 274,
    type: "text",
    label: "Date/Time",
    pdfFieldName: "DateTime_2",
  },
  {
    id: "p12_f275",
    page: 12,
    index: 275,
    type: "text",
    label: "Address",
    pdfFieldName: "Address_3",
  },
  {
    id: "p12_f276",
    page: 12,
    index: 276,
    type: "text",
    label: "Phone",
    pdfFieldName: "Phone_8",
  },
  {
    id: "p12_f277",
    page: 12,
    index: 277,
    type: "text",
    label: "City",
    pdfFieldName: "City_6",
  },
  {
    id: "p12_f278",
    page: 12,
    index: 278,
    type: "text",
    label: "State",
    pdfFieldName: "State_6",
  },
  {
    id: "p12_f279",
    page: 12,
    index: 279,
    type: "text",
    label: "Zip",
    pdfFieldName: "Zip_6",
  },
  {
    id: "p12_f280",
    page: 12,
    index: 280,
    type: "text",
    label: "Fax",
    pdfFieldName: "Fax_3",
  },
] as const;

export function trecFormFieldsForStep(
  step: number,
): readonly TrecFormFieldDefinition[] {
  const firstPage = step * 2 + 1;
  return TREC_20_19_FIELDS.filter(
    (field) => field.page === firstPage || field.page === firstPage + 1,
  );
}
