export type TrecFormLibraryCategory = 'Contracts' | 'Contract Addenda' | 'Other Forms' | 'TR Forms';

export type TrecFormLibraryItem = {
  formFamily: string;
  formNumber: string;
  title: string;
  effectiveDate: string;
  category: TrecFormLibraryCategory;
  pdfUrl: string;
  local: boolean;
};

// Texas REALTORS (TXR) forms are disabled until a forms license is in place.
// Set to true to bring the section back (also restore public/forms/trec-library/txr-*.pdf from private-forms/).
export const TXR_FORMS_ENABLED = false;

const ALL_FORM_LIBRARY: TrecFormLibraryItem[] = [
  { formFamily: '39', formNumber: '39-11', title: 'Amendment to Contract', effectiveDate: '2026-07-01', category: 'Contracts', pdfUrl: '/forms/trec-library/trec-39-11.pdf', local: true },
  { formFamily: '25', formNumber: '25-17', title: 'Farm and Ranch Contract', effectiveDate: '2026-07-01', category: 'Contracts', pdfUrl: '/forms/trec-library/trec-25-17.pdf', local: true },
  { formFamily: '24', formNumber: '24-20', title: 'New Home Contract (Completed Construction)', effectiveDate: '2026-07-01', category: 'Contracts', pdfUrl: '/forms/trec-library/trec-24-20.pdf', local: true },
  { formFamily: '23', formNumber: '23-20', title: 'New Home Contract (Incomplete Construction)', effectiveDate: '2026-07-01', category: 'Contracts', pdfUrl: '/forms/trec-library/trec-23-20.pdf', local: true },
  { formFamily: '20', formNumber: '20-19', title: 'One to Four Family Residential Contract (Resale)', effectiveDate: '2026-07-01', category: 'Contracts', pdfUrl: '/forms/trec-20-19.pdf', local: true },
  { formFamily: '30', formNumber: '30-18', title: 'Residential Condominium Contract (Resale)', effectiveDate: '2026-07-01', category: 'Contracts', pdfUrl: '/forms/trec-library/trec-30-18.pdf', local: true },
  { formFamily: '9', formNumber: '9-18', title: 'Unimproved Property Contract', effectiveDate: '2026-07-01', category: 'Contracts', pdfUrl: '/forms/trec-library/trec-9-18.pdf', local: true },

  { formFamily: '49', formNumber: '49-1', title: "Addendum Concerning Right to Terminate Due to Lender's Appraisal", effectiveDate: '2019-03-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-49-1.pdf', local: true },
  { formFamily: '53', formNumber: '53-0', title: 'Addendum Containing Notice of Obligation to Pay Improvement District Assessment', effectiveDate: '2021-09-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-53-0.pdf', local: true },
  { formFamily: '11', formNumber: '11-9', title: 'Addendum for "Back-Up" Contract', effectiveDate: '2026-07-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-11-9.pdf', local: true },
  { formFamily: '48', formNumber: '48-1', title: 'Addendum for Authorizing Hydrostatic Testing', effectiveDate: '2020-03-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-48-1.pdf', local: true },
  { formFamily: '33', formNumber: '33-2', title: 'Addendum for Coastal Area Property', effectiveDate: '2011-12-05', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-33-2.pdf', local: true },
  { formFamily: '47', formNumber: '47-0', title: 'Addendum for Property in a Propane Gas System Service Area', effectiveDate: '2014-02-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-47-0.pdf', local: true },
  { formFamily: '34', formNumber: '34-4', title: 'Addendum for Property Located Seaward of the Gulf Intracoastal Waterway', effectiveDate: '2011-12-05', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-34-4.pdf', local: true },
  { formFamily: '36', formNumber: '36-11', title: 'Addendum for Property Subject to Mandatory Membership in a Property Owners Association', effectiveDate: '2026-07-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-36-11.pdf', local: true },
  { formFamily: '12', formNumber: '12-3', title: "Addendum for Release of Liability on Assumed Loan and/or Restoration of Seller's VA Entitlement", effectiveDate: '2011-12-05', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-12-3.pdf', local: true },
  { formFamily: '44', formNumber: '44-3', title: 'Addendum for Reservation of Oil, Gas, and Other Minerals', effectiveDate: '2023-02-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-44-3.pdf', local: true },
  { formFamily: '10', formNumber: '10-6', title: 'Addendum for Sale of Other Property by Buyer', effectiveDate: '2011-12-05', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-10-6.pdf', local: true },
  { formFamily: '60', formNumber: '60-0', title: 'Addendum for Section 1031 Exchange', effectiveDate: '2025-01-03', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-60-0.pdf', local: true },
  { formFamily: '56', formNumber: '56-0', title: "Addendum for Seller's Disclosure of Information on Lead-Based Paint and Lead-Based Paint Hazards as Required by Federal Law", effectiveDate: '2026-05-28', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-56-0.pdf', local: true },
  { formFamily: '52', formNumber: '52-1', title: 'Addendum Regarding Fixture Leases', effectiveDate: '2023-02-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-52-1.pdf', local: true },
  { formFamily: '51', formNumber: '51-1', title: 'Addendum Regarding Residential Leases', effectiveDate: '2023-02-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-51-1.pdf', local: true },
  { formFamily: '16', formNumber: '16-7', title: "Buyer's Temporary Residential Lease", effectiveDate: '2026-01-05', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-16-7.pdf', local: true },
  { formFamily: '28', formNumber: '28-2', title: 'Environmental Assessment, Threatened or Endangered Species, and Wetlands Addendum', effectiveDate: '2011-12-05', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-28-2.pdf', local: true },
  { formFamily: '41', formNumber: '41-3', title: 'Loan Assumption Addendum', effectiveDate: '2023-02-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-41-3.pdf', local: true },
  { formFamily: '57', formNumber: '57-0', title: 'Non-Realty Items Addendum', effectiveDate: '2025-09-03', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-57-0.pdf', local: true },
  { formFamily: '26', formNumber: '26-8', title: 'Seller Financing Addendum', effectiveDate: '2023-02-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-26-8.pdf', local: true },
  { formFamily: '15', formNumber: '15-7', title: "Seller's Temporary Residential Lease", effectiveDate: '2026-01-05', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-15-7.pdf', local: true },
  { formFamily: '45', formNumber: '45-2', title: 'Short Sale Addendum', effectiveDate: '2021-04-01', category: 'Contract Addenda', pdfUrl: '/forms/trec-library/trec-45-2.pdf', local: true },
  { formFamily: '40', formNumber: '40-11', title: 'Third Party Financing Addendum', effectiveDate: '2025-01-03', category: 'Contract Addenda', pdfUrl: '/forms/trec-40-11.pdf', local: true },

  { formFamily: '32', formNumber: '32-5', title: 'Condominium Resale Certificate', effectiveDate: '2024-11-25', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-32-5.pdf', local: true },
  { formFamily: 'RSC', formNumber: 'RSC-4', title: 'Disclosure of Relationship with Contract Provider or Administrator', effectiveDate: '2023-06-11', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-RSC-4.pdf', local: true },
  { formFamily: '54', formNumber: '54-1', title: "Landlord's Floodplain and Flood Notice", effectiveDate: '2025-11-26', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-54-1.pdf', local: true },
  { formFamily: '38', formNumber: '38-8', title: "Notice of Buyer's Termination of Contract", effectiveDate: '2025-04-01', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-38-8.pdf', local: true },
  { formFamily: '50', formNumber: '50-0', title: "Notice of Seller's Termination of Contract", effectiveDate: '2018-08-13', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-50-0.pdf', local: true },
  { formFamily: '58', formNumber: '58-0', title: 'Notice to Prospective Buyer', effectiveDate: '2025-09-03', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-58-0.pdf', local: true },
  { formFamily: '59', formNumber: '59-0', title: 'Notice to Purchaser of Special Taxing or Assessment District', effectiveDate: '2024-02-12', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-59-0.pdf', local: true },
  { formFamily: 'REI-7', formNumber: 'REI 7-6', title: 'Property Inspection Report', effectiveDate: '2022-02-01', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-REI-7-6.pdf', local: true },
  { formFamily: '61', formNumber: '61-0', title: "Seller's Disclosure about Groundwater and Surface Water Rights", effectiveDate: '2026-07-01', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-61-0.pdf', local: true },
  { formFamily: '55', formNumber: '55-1', title: "Seller's Disclosure Notice", effectiveDate: '2026-05-28', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-55-1.pdf', local: true },
  { formFamily: '62', formNumber: '62-0', title: 'Seller\'s Notice to Buyer of Removal of Contingency Under Addendum for "Back-Up" Contract', effectiveDate: '2026-05-28', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-62-0.pdf', local: true },
  { formFamily: '37', formNumber: '37-5', title: "Subdivision Information, Including Resale Certificate for Property Subject to Mandatory Membership in a Property Owners' Association", effectiveDate: '2014-02-10', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-37-5.pdf', local: true },
  { formFamily: 'TXR1102', formNumber: 'TXR 1102', title: 'Residential Real Estate Listing Agreement, Exclusive Right to Lease', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1102.pdf', local: true },
  { formFamily: 'TXR1201', formNumber: 'TXR 1201', title: 'Farm and Ranch Real Estate Listing Agreement, Exclusive Right to Sell', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1201.pdf', local: true },
  { formFamily: 'TXR1302', formNumber: 'TXR 1302', title: 'Commercial Real Estate Listing Agreement - Exclusive Right to Lease', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1302.pdf', local: true },
  { formFamily: 'TXR1303', formNumber: 'TXR 1303', title: 'Commercial Real Estate Listing Agreement - Exclusive Right to Sublease', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1303.pdf', local: true },
  { formFamily: 'TXR1401', formNumber: 'TXR 1401', title: 'Condominium Addendum to Listing', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1401.pdf', local: true },
  { formFamily: 'TXR1402', formNumber: 'TXR 1402', title: 'Named Exclusions Addendum to Listing', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1402.pdf', local: true },
  { formFamily: 'TXR1403', formNumber: 'TXR 1403', title: 'Exclusive Agency Addendum to Listing', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1403.pdf', local: true },
  { formFamily: 'TXR1404', formNumber: 'TXR 1404', title: 'Amendment to Listing', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1404.pdf', local: true },
  { formFamily: 'TXR1405', formNumber: 'TXR 1405', title: "Request for Information from an Owners' Association", effectiveDate: '2012-03-02', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1405.pdf', local: true },
  { formFamily: 'TXR1406', formNumber: 'TXR 1406', title: "Seller's Disclosure Notice", effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1406.pdf', local: true },
  { formFamily: 'TXR1407', formNumber: 'TXR 1407', title: 'Information About On-Site Sewer Facility', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1407.pdf', local: true },
  { formFamily: 'TXR1408', formNumber: 'TXR 1408', title: 'Commercial Property Condition Statement', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1408.pdf', local: true },
  { formFamily: 'TXR1409', formNumber: 'TXR 1409', title: 'Intermediary Relationship Notification', effectiveDate: '2024-08-23', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1409.pdf', local: true },
  { formFamily: 'TXR1410', formNumber: 'TXR 1410', title: 'Termination of Listing', effectiveDate: '2006-04-14', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1410.pdf', local: true },
  { formFamily: 'TXR1411', formNumber: 'TXR 1411', title: 'Keybox Authorization by Tenant', effectiveDate: '2004-01-07', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1411.pdf', local: true },
  { formFamily: 'TXR1412', formNumber: 'TXR 1412', title: "Seller's Authorization to Release and Advertise Certain Information", effectiveDate: '2024-06-24', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1412.pdf', local: true },
  { formFamily: 'TXR1413', formNumber: 'TXR 1413', title: 'Request for Mortgage Information', effectiveDate: '2004-01-07', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1413.pdf', local: true },
  { formFamily: 'TXR1414', formNumber: 'TXR 1414', title: 'Information About Special Flood Hazard Areas', effectiveDate: '2021-10-19', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1414.pdf', local: true },
  { formFamily: 'TXR1415', formNumber: 'TXR 1415', title: 'Residential Listing Checklist', effectiveDate: '2016-01-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1415.pdf', local: true },
  { formFamily: 'TXR1417', formNumber: 'TXR 1417', title: 'Representation Disclosure', effectiveDate: '2024-08-23', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1417.pdf', local: true },
  { formFamily: 'TXR1418', formNumber: 'TXR 1418', title: "Update to Seller's Disclosure Notice", effectiveDate: '2018-02-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1418.pdf', local: true },
  { formFamily: 'TXR1419', formNumber: 'TXR 1419', title: 'Commercial Listing Agreement Termination', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1419.pdf', local: true },
  { formFamily: 'TXR1501', formNumber: 'TXR 1501', title: 'Residential Buyer/Tenant Representation Agreement', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1501.pdf', local: true },
  { formFamily: 'TXR1502', formNumber: 'TXR 1502', title: 'Commercial Buyer/Tenant Representation Agreement', effectiveDate: '2025-09-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1502.pdf', local: true },
  { formFamily: 'TXR1503', formNumber: 'TXR 1503', title: 'Termination of Buyer/Tenant Representation Agreement', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1503.pdf', local: true },
  { formFamily: 'TXR1504', formNumber: 'TXR 1504', title: "Notice from Buyer's Agent to Seller", effectiveDate: '2024-08-23', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1504.pdf', local: true },
  { formFamily: 'TXR1505', formNumber: 'TXR 1505', title: 'Amendment to Buyer/Tenant Representation Agreement', effectiveDate: '2024-08-23', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1505.pdf', local: true },
  { formFamily: 'TXR1506', formNumber: 'TXR 1506', title: 'General Information and Notice to Consumers', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1506.pdf', local: true },
  { formFamily: 'TXR1507', formNumber: 'TXR 1507', title: 'Residential Buyer/Tenant Representation Agreement, Short Form', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1507.pdf', local: true },
  { formFamily: 'TXR1608', formNumber: 'TXR 1608', title: 'New Residential Condominium Contract (Completed Construction)', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1608.pdf', local: true },
  { formFamily: 'TXR1609', formNumber: 'TXR 1609', title: 'New Residential Condominium Contract (Incomplete Construction)', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1609.pdf', local: true },
  { formFamily: 'TXR1801', formNumber: 'TXR 1801', title: 'Commercial Contract - Improved Property', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1801.pdf', local: true },
  { formFamily: 'TXR1802', formNumber: 'TXR 1802', title: 'Commercial Contract - Unimproved Property', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1802.pdf', local: true },
  { formFamily: 'TXR1803', formNumber: 'TXR 1803', title: 'Commercial Letter of Intent to Purchase', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1803.pdf', local: true },
  { formFamily: 'TXR1904', formNumber: 'TXR 1904', title: 'Release of Earnest Money', effectiveDate: '2002-02-06', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1904.pdf', local: true },
  { formFamily: 'TXR1907', formNumber: 'TXR 1907', title: 'T-47 Residential Real Property Affidavit', effectiveDate: '2024-11-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1907.pdf', local: true },
  { formFamily: 'TXR1912', formNumber: 'TXR 1912', title: 'Notices Regarding Contingency Under Addendum for Sale of Other Property by Buyer', effectiveDate: '2018-02-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1912.pdf', local: true },
  { formFamily: 'TXR1925', formNumber: 'TXR 1925', title: "Buyer's Walk-Through, Confirmation, and Acceptance Form", effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1925.pdf', local: true },
  { formFamily: 'TXR1926', formNumber: 'TXR 1926', title: "Seller's Invitation to Buyer to Submit New Offer", effectiveDate: '2004-08-27', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1926.pdf', local: true },
  { formFamily: 'TXR1929', formNumber: 'TXR 1929', title: 'Authorization to Obtain Consumer Report', effectiveDate: '1998-01-27', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1929.pdf', local: true },
  { formFamily: 'TXR1930', formNumber: 'TXR 1930', title: 'Commercial Contract Condominium Addendum', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1930.pdf', local: true },
  { formFamily: 'TXR1931', formNumber: 'TXR 1931', title: 'Commercial Contract Financing Addendum', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1931.pdf', local: true },
  { formFamily: 'TXR1932', formNumber: 'TXR 1932', title: 'Commercial Contract Amendment', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1932.pdf', local: true },
  { formFamily: 'TXR1933', formNumber: 'TXR 1933', title: 'Condominium Conversion Addendum', effectiveDate: '2003-01-02', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1933.pdf', local: true },
  { formFamily: 'TXR1934', formNumber: 'TXR 1934', title: 'Condominium Information Statement', effectiveDate: '2003-01-02', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1934.pdf', local: true },
  { formFamily: 'TXR1935', formNumber: 'TXR 1935', title: "Seller's Estimated Net Proceeds", effectiveDate: '2018-02-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1935.pdf', local: true },
  { formFamily: 'TXR1936', formNumber: 'TXR 1936', title: "Approximation of Buyer's Closing Costs", effectiveDate: '2018-02-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1936.pdf', local: true },
  { formFamily: 'TXR1937', formNumber: 'TXR 1937', title: 'Commercial Contract Exhibit', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1937.pdf', local: true },
  { formFamily: 'TXR1938', formNumber: 'TXR 1938', title: 'Commercial Tenant Estoppel Certificate', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1938.pdf', local: true },
  { formFamily: 'TXR1939', formNumber: 'TXR 1939', title: 'Commercial Contract Termination Notice', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1939.pdf', local: true },
  { formFamily: 'TXR1940', formNumber: 'TXR 1940', title: 'Commercial Contract Special Provisions Addendum', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1940.pdf', local: true },
  { formFamily: 'TXR1941', formNumber: 'TXR 1941', title: 'Relocation Addendum', effectiveDate: '2021-03-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1941.pdf', local: true },
  { formFamily: 'TXR1942', formNumber: 'TXR 1942', title: 'Commercial Contract Critical Date List', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1942.pdf', local: true },
  { formFamily: 'TXR1943', formNumber: 'TXR 1943', title: 'Commercial Contract Assignment of Buyer’s Interest', effectiveDate: '2014-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1943.pdf', local: true },
  { formFamily: 'TXR1945', formNumber: 'TXR 1945', title: 'Notice of Withdrawal of Offer', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1945.pdf', local: true },
  { formFamily: 'TXR1946', formNumber: 'TXR 1946', title: 'Commercial Contract Condominium Addendum (Incomplete Construction)', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1946.pdf', local: true },
  { formFamily: 'TXR1947', formNumber: 'TXR 1947', title: 'Commercial Request for Evaluation Materials and Confidentiality Agreement', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1947.pdf', local: true },
  { formFamily: 'TXR2001', formNumber: 'TXR 2001', title: 'Residential Lease', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2001.pdf', local: true },
  { formFamily: 'TXR2002', formNumber: 'TXR 2002', title: 'Agreement Between Brokers for Residential Leases', effectiveDate: '2003-10-14', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2002.pdf', local: true },
  { formFamily: 'TXR2003', formNumber: 'TXR 2003', title: 'Residential Lease Application', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2003.pdf', local: true },
  { formFamily: 'TXR2004', formNumber: 'TXR 2004', title: 'Animal Agreement', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2004.pdf', local: true },
  { formFamily: 'TXR2005', formNumber: 'TXR 2005', title: 'Extension of Residential Lease', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2005.pdf', local: true },
  { formFamily: 'TXR2006', formNumber: 'TXR 2006', title: 'Residential Lease Inventory and Condition Form', effectiveDate: '2024-05-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2006.pdf', local: true },
  { formFamily: 'TXR2007', formNumber: 'TXR 2007', title: 'Residential Lease Guaranty', effectiveDate: '2024-05-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2007.pdf', local: true },
  { formFamily: 'TXR2008', formNumber: 'TXR 2008', title: 'Addendum Regarding Lead-Based Paint', effectiveDate: '2003-10-14', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2008.pdf', local: true },
  { formFamily: 'TXR2010', formNumber: 'TXR 2010', title: 'Pool/Spa Maintenance Addendum', effectiveDate: '2003-10-14', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2010.pdf', local: true },
  { formFamily: 'TXR2011', formNumber: 'TXR 2011', title: 'Residential Lease for a Multi-Family Property Unit', effectiveDate: '2026-01-06', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2011.pdf', local: true },
  { formFamily: 'TXR2012', formNumber: 'TXR 2012', title: 'Early Termination of Residential Lease', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2012.pdf', local: true },
  { formFamily: 'TXR2013', formNumber: 'TXR 2013', title: 'Bed Bug Addendum', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2013.pdf', local: true },
  { formFamily: 'TXR2014', formNumber: 'TXR 2014', title: 'Residential Lease Amendment', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2014.pdf', local: true },
  { formFamily: 'TXR2015', formNumber: 'TXR 2015', title: 'Addendum Regarding Rental Flood Disclosure', effectiveDate: '2025-09-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2015.pdf', local: true },
  { formFamily: 'TXR2016', formNumber: 'TXR 2016', title: 'Tenant and Occupant Information', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2016.pdf', local: true },
  { formFamily: 'TXR2017', formNumber: 'TXR 2017', title: 'Residential Lease Sight Unseen Addendum', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2017.pdf', local: true },
  { formFamily: 'TXR2018', formNumber: 'TXR 2018', title: 'Addendum Regarding Fee in Lieu of a Security Deposit', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2018.pdf', local: true },
  { formFamily: 'TXR2101', formNumber: 'TXR 2101', title: 'Commercial Lease', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2101.pdf', local: true },
  { formFamily: 'TXR2102', formNumber: 'TXR 2102', title: "Commercial Lease Addendum for Broker's Fee", effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2102.pdf', local: true },
  { formFamily: 'TXR2104', formNumber: 'TXR 2104', title: 'Commercial Lease Addendum for Extension of Term', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2104.pdf', local: true },
  { formFamily: 'TXR2105', formNumber: 'TXR 2105', title: "Commercial Lease Addendum For Tenant's Right of First Refusal", effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2105.pdf', local: true },
  { formFamily: 'TXR2106', formNumber: 'TXR 2106', title: 'Commercial Lease Addendum for Percentage Rent', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2106.pdf', local: true },
  { formFamily: 'TXR2107', formNumber: 'TXR 2107', title: 'Commercial Lease Addendum for Parking', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2107.pdf', local: true },
  { formFamily: 'TXR2108', formNumber: 'TXR 2108', title: "Commercial Landlord's Rules and Regulations", effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2108.pdf', local: true },
  { formFamily: 'TXR2109', formNumber: 'TXR 2109', title: 'Commercial Lease Guaranty', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2109.pdf', local: true },
  { formFamily: 'TXR2110', formNumber: 'TXR 2110', title: "Commercial Lease Addendum for Tenant's Option for Additional Space", effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2110.pdf', local: true },
  { formFamily: 'TXR2111', formNumber: 'TXR 2111', title: 'Commercial Lease Construction Addendum (Landlord to Complete Construction)', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2111.pdf', local: true },
  { formFamily: 'TXR2112', formNumber: 'TXR 2112', title: 'Commercial Lease Construction Addendum (Tenant to Complete Construction)', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2112.pdf', local: true },
  { formFamily: 'TXR2113', formNumber: 'TXR 2113', title: 'Commercial Lease Acceptance Form', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2113.pdf', local: true },
  { formFamily: 'TXR2114', formNumber: 'TXR 2114', title: 'Commercial Lease Amendment', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2114.pdf', local: true },
  { formFamily: 'TXR2115', formNumber: 'TXR 2115', title: 'Commercial Lease Exhibit', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2115.pdf', local: true },
  { formFamily: 'TXR2116', formNumber: 'TXR 2116', title: 'Commercial Sublease', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2116.pdf', local: true },
  { formFamily: 'TXR2117', formNumber: 'TXR 2117', title: "Commercial Landlord's Consent to Sublease", effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2117.pdf', local: true },
  { formFamily: 'TXR2118', formNumber: 'TXR 2118', title: "Commercial Sublease Addendum for Broker's Fee", effectiveDate: '2014-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2118.pdf', local: true },
  { formFamily: 'TXR2119', formNumber: 'TXR 2119', title: 'Commercial Lease Addendum for Contingencies', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2119.pdf', local: true },
  { formFamily: 'TXR2120', formNumber: 'TXR 2120', title: 'Commercial Lease Application', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2120.pdf', local: true },
  { formFamily: 'TXR2121', formNumber: 'TXR 2121', title: 'Commercial Lease Inventory and Condition Form', effectiveDate: '2010-01-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2121.pdf', local: true },
  { formFamily: 'TXR2122', formNumber: 'TXR 2122', title: 'Commercial Letter of Intent to Lease', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2122.pdf', local: true },
  { formFamily: 'TXR2124', formNumber: 'TXR 2124', title: 'Commercial Sublease Guaranty', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2124.pdf', local: true },
  { formFamily: 'TXR2125', formNumber: 'TXR 2125', title: 'Commercial Lease Special Provisions Addendum', effectiveDate: '2018-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2125.pdf', local: true },
  { formFamily: 'TXR2126', formNumber: 'TXR 2126', title: 'Commercial Lease Rent Forbearance Agreement', effectiveDate: '2020-04-03', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2126.pdf', local: true },
  { formFamily: 'TXR2201', formNumber: 'TXR 2201', title: 'Residential Leasing and Property Management Agreement', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2201.pdf', local: true },
  { formFamily: 'TXR2202', formNumber: 'TXR 2202', title: 'Commercial Property Management Agreement', effectiveDate: '2014-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2202.pdf', local: true },
  { formFamily: 'TXR2203', formNumber: 'TXR 2203', title: 'Commercial Amendment to Property Management Agreement', effectiveDate: '2014-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2203.pdf', local: true },
  { formFamily: 'TXR2204', formNumber: 'TXR 2204', title: 'Multiple Property Addendum', effectiveDate: '2004-08-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2204.pdf', local: true },
  { formFamily: 'TXR2205', formNumber: 'TXR 2205', title: "Addendum for Authorization to Act for Owner Before Owners' Association", effectiveDate: '2014-01-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2205.pdf', local: true },
  { formFamily: 'TXR2206', formNumber: 'TXR 2206', title: "Owner's Notice Concerning Condition of Property Under Property Management Agreement", effectiveDate: '2004-08-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2206.pdf', local: true },
  { formFamily: 'TXR2207', formNumber: 'TXR 2207', title: "Property Manager's Inventory and Condition Report", effectiveDate: '2004-08-26', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2207.pdf', local: true },
  { formFamily: 'TXR2208', formNumber: 'TXR 2208', title: 'Notice To Vacate', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2208.pdf', local: true },
  { formFamily: 'TXR2210', formNumber: 'TXR 2210', title: 'Notice to Tenant of Change in Management and Accountability for Security Deposit', effectiveDate: '2014-01-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2210.pdf', local: true },
  { formFamily: 'TXR2211', formNumber: 'TXR 2211', title: 'Lease Amendment Concerning Tenant Change', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2211.pdf', local: true },
  { formFamily: 'TXR2212', formNumber: 'TXR 2212', title: 'Adverse Action Notice and Credit Score Disclosure', effectiveDate: '2012-01-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2212.pdf', local: true },
  { formFamily: 'TXR2213', formNumber: 'TXR 2213', title: 'Agreement to Pay Past Due Amounts Under Lease', effectiveDate: '2007-04-13', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2213.pdf', local: true },
  { formFamily: 'TXR2214', formNumber: 'TXR 2214', title: 'Request for Rental History', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2214.pdf', local: true },
  { formFamily: 'TXR2215', formNumber: 'TXR 2215', title: 'Report of Incident Occurring on Property', effectiveDate: '2007-04-13', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2215.pdf', local: true },
  { formFamily: 'TXR2216', formNumber: 'TXR 2216', title: 'Itemization of Security Deposit', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2216.pdf', local: true },
  { formFamily: 'TXR2217', formNumber: 'TXR 2217', title: "Notice of Landlord's Intent Not to Renew", effectiveDate: '2007-04-13', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2217.pdf', local: true },
  { formFamily: 'TXR2218', formNumber: 'TXR 2218', title: "Notice of Tenant's Intent to Vacate", effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2218.pdf', local: true },
  { formFamily: 'TXR2219', formNumber: 'TXR 2219', title: 'Request for Employment Verification', effectiveDate: '2009-02-06', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2219.pdf', local: true },
  { formFamily: 'TXR2220', formNumber: 'TXR 2220', title: 'General Information for Tenant of Property Facing Foreclosure', effectiveDate: '2018-06-23', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2220.pdf', local: true },
  { formFamily: 'TXR2221', formNumber: 'TXR 2221', title: 'Amendment to Residential Leasing and Property Management Agreement', effectiveDate: '2010-06-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2221.pdf', local: true },
  { formFamily: 'TXR2222', formNumber: 'TXR 2222', title: 'Notice of Termination of Residential Leasing and Property Management Agreement', effectiveDate: '2025-02-03', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2222.pdf', local: true },
  { formFamily: 'TXR2223', formNumber: 'TXR 2223', title: "Owner's Authorization Concerning Unescorted Access to Property", effectiveDate: '2017-03-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2223.pdf', local: true },
  { formFamily: 'TXR2224', formNumber: 'TXR 2224', title: 'Notice of Abandonment', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2224.pdf', local: true },
  { formFamily: 'TXR2225', formNumber: 'TXR 2225', title: 'Response to Request for Assistance Animal', effectiveDate: '2024-05-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2225.pdf', local: true },
  { formFamily: 'TXR2226', formNumber: 'TXR 2226', title: 'General Information for Landlord Regarding Assistance Animals', effectiveDate: '2024-05-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2226.pdf', local: true },
  { formFamily: 'TXR2228', formNumber: 'TXR 2228', title: 'Residential Tenant Estoppel Certificate', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2228.pdf', local: true },
  { formFamily: 'TXR2229', formNumber: 'TXR 2229', title: 'Notice of Termination Due to Casualty Loss', effectiveDate: '2022-07-08', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2229.pdf', local: true },
  { formFamily: 'TXR2230', formNumber: 'TXR 2230', title: 'Notice of Late Rent Breach of Lease', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2230.pdf', local: true },
  { formFamily: 'TXR2231', formNumber: 'TXR 2231', title: 'Notice of Non-Rent Breach of Lease', effectiveDate: '2024-05-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2231.pdf', local: true },
  { formFamily: 'TXR2301', formNumber: 'TXR 2301', title: 'Independent Contractor Agreement for Sales Associate', effectiveDate: '2024-06-24', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2301.pdf', local: true },
  { formFamily: 'TXR2302', formNumber: 'TXR 2302', title: 'Statement of Understanding', effectiveDate: '2007-08-16', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2302.pdf', local: true },
  { formFamily: 'TXR2303', formNumber: 'TXR 2303', title: 'Brokerage Policies and Procedures Acknowledgment and Agreement', effectiveDate: '2013-07-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2303.pdf', local: true },
  { formFamily: 'TXR2401', formNumber: 'TXR 2401', title: 'Registration Agreement Between Broker and Owner', effectiveDate: '2024-06-24', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2401.pdf', local: true },
  { formFamily: 'TXR2402', formNumber: 'TXR 2402', title: 'Registration Agreement Between Brokers', effectiveDate: '2024-08-23', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2402.pdf', local: true },
  { formFamily: 'TXR2403', formNumber: 'TXR 2403', title: 'Commercial Registration Agreement Between Broker and Owner', effectiveDate: '2026-01-05', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2403.pdf', local: true },
  { formFamily: 'TXR2404', formNumber: 'TXR 2404', title: 'Commercial Registration Agreement Between Brokers', effectiveDate: '2014-04-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2404.pdf', local: true },
  { formFamily: 'TXR2405', formNumber: 'TXR 2405', title: 'Referral Agreement Between Brokers', effectiveDate: '2024-06-24', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2405.pdf', local: true },
  { formFamily: 'TXR2502', formNumber: 'TXR 2502', title: 'Notice of Information from Other Sources', effectiveDate: '2008-07-16', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2502.pdf', local: true },
  { formFamily: 'TXR2506', formNumber: 'TXR 2506', title: 'Inspector Notice', effectiveDate: '2014-01-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2506.pdf', local: true },
  { formFamily: 'TXR2508', formNumber: 'TXR 2508', title: 'Information About Property Insurance for a Buyer or Seller', effectiveDate: '2014-02-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2508.pdf', local: true },
  { formFamily: 'TXR2509', formNumber: 'TXR 2509', title: 'Information About Mineral Clauses in Contract Forms', effectiveDate: '2021-10-18', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2509.pdf', local: true },
  { formFamily: 'TXR2516', formNumber: 'TXR 2516', title: 'Authorization to Furnish TILA-RESPA Integrated Disclosures', effectiveDate: '2015-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2516.pdf', local: true },
  { formFamily: 'TXR2517', formNumber: 'TXR 2517', title: 'Wire Fraud Warning', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2517.pdf', local: true },
  { formFamily: 'TXR2518', formNumber: 'TXR 2518', title: 'Information Regarding Windstorm and Hail Insurance for Certain Properties', effectiveDate: '2018-02-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2518.pdf', local: true },
  { formFamily: 'TXR2519', formNumber: 'TXR 2519', title: 'Information Regarding Property Near an International Border', effectiveDate: '2018-02-01', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-2519.pdf', local: true },
  { formFamily: 'TXR1101', formNumber: 'TXR 1101', title: 'Residential Real Estate Listing Agreement (Exclusive Right To Sell)', effectiveDate: '2026-06-15', category: 'TR Forms', pdfUrl: '/forms/trec-library/txr-1101.pdf', local: true },
  { formFamily: 'IABS', formNumber: 'IABS 1-2', title: 'Information About Brokerage Services', effectiveDate: '2026-01-01', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-IABS-1-2.pdf', local: true },
  { formFamily: 'CN', formNumber: 'CN 1-5', title: 'Consumer Protection Notice', effectiveDate: '2023-09-01', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-CN-1-5.pdf', local: true },
  { formFamily: 'ERW', formNumber: 'ERW 4-1', title: 'Notice Concerning Easements and Rights-of-Way', effectiveDate: '2016-08-18', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-ERW-4-1.pdf', local: true },
  { formFamily: 'OP-I', formNumber: 'OP-I', title: 'Texas Real Estate Consumer Notice Concerning Hazards or Deficiencies', effectiveDate: '2015-05-04', category: 'Other Forms', pdfUrl: '/forms/trec-library/trec-OP-I.pdf', local: true },
];

export const TREC_FORM_LIBRARY: TrecFormLibraryItem[] = ALL_FORM_LIBRARY.filter(
  (form) => TXR_FORMS_ENABLED || form.category !== 'TR Forms',
);

const ALL_CATEGORIES: Array<'All Forms' | TrecFormLibraryCategory> = [
  'All Forms',
  'Contracts',
  'Contract Addenda',
  'Other Forms',
  'TR Forms',
];

export const TREC_FORM_LIBRARY_CATEGORIES = ALL_CATEGORIES.filter(
  (category) => TXR_FORMS_ENABLED || category !== 'TR Forms',
);
