import type { TrecFormFieldDefinition, TrecFormFieldType } from './trec-20-19-fields';

type EmbeddedField = readonly [page: number, type: TrecFormFieldType, pdfFieldName: string];

function buildFields(formNumber: string, fields: readonly EmbeddedField[]): TrecFormFieldDefinition[] {
  return fields.map(([page, type, pdfFieldName], index) => ({
    id: `trec_${formNumber.replace(/[^a-z0-9]/gi, '_')}_p${String(page).padStart(2, '0')}_f${String(index + 1).padStart(3, '0')}`,
    page,
    index: index + 1,
    type,
    label: pdfFieldName,
    pdfFieldName,
  }));
}

const TREC_40_11_EMBEDDED_FIELDS: readonly EmbeddedField[] = [
  [1, 'text', 'Street Address and City'],
  [1, 'text', 'years with interest not to exceed'],
  [1, 'checkbox', '1 Conventional Financing'],
  [1, 'checkbox', '2 Texas Veterans Loan A loans from the Texas Veterans Land Board of'],
  [1, 'checkbox', '3 FHA Insured Financing A Section'],
  [1, 'checkbox', '4 VA Guaranteed Financing A VA guaranteed loan of not less than'],
  [1, 'checkbox', '5 USDA Guaranteed Financing A USDAguaranteed loan of not less than'],
  [1, 'checkbox', 'a A first mortgage loan in the principal amount of'],
  [1, 'checkbox', 'b A second mortgage loan in the principal amount of'],
  [1, 'text', 'any financed PMI premium due in full in 1'],
  [1, 'text', 'any financed PMI premium due in full in 2'],
  [1, 'text', 'per annum for the first'],
  [1, 'text', 'shown on Buyers Loan Estimate for the loan not to exceed'],
  [1, 'text', 'excluding'],
  [1, 'text', 'any financed PMI premium due in full in 1_2'],
  [1, 'text', 'any financed PMI premium due in full in 2_2'],
  [1, 'text', 'per annum for the first_2'],
  [1, 'text', 'shown on Buyers Loan Estimate for the loan not to exceed_2'],
  [1, 'text', 'for a period in the total amount of'],
  [1, 'text', 'years at the interest rate established by the'],
  [1, 'text', 'undefined'],
  [1, 'text', 'excluding any financed MIP amortizable monthly for not less'],
  [1, 'text', 'than'],
  [1, 'text', 'years with interest not to exceed_2'],
  [1, 'text', 'Charges as shown on Buyers Loan Estimate for the loan not to exceed'],
  [1, 'text', 'excluding any financed Funding Fee amortizable monthly for not less than'],
  [1, 'text', 'years'],
  [1, 'text', 'with interest not to exceed'],
  [1, 'text', 'per annum for the first_4'],
  [1, 'text', 'Origination Charges as shown on Buyers Loan Estimate for the loan not to exceed'],
  [1, 'text', 'any financed PMI premium or other costs with interest not to exceed'],
  [1, 'text', 'Initialed for identification by Buyer'],
  [1, 'text', 'undefined_2'],
  [1, 'text', 'and Seller'],
  [1, 'text', 'undefined_3'],
  [2, 'text', 'Address of Property'],
  [2, 'checkbox', 'This contract is subject to Buyer obtaining Buyer Approval If Buyer cannot obtain Buyer'],
  [2, 'text', 'value of the Property established by the Department of Veterans Affairs'],
  [2, 'text', 'Signature1'],
  [2, 'text', 'Signature2'],
  [2, 'text', 'Signature3'],
  [2, 'text', 'Signature4'],
  [1, 'text', 'Text1'],
  [1, 'text', 'for the first'],
  [1, 'text', 'Estimate for the loan not to exceed'],
  [1, 'checkbox', 'will not be an FHA insured loan'],
  [2, 'checkbox', 'Check Box2'],
  [2, 'text', 'Conversion Mortgage loan in the original principal amount of'],
  [1, 'text', 'not to exceed'],
  [1, 'checkbox', '6 Reverse Mortgage Financing A reverse mortgage loan also known as a Home Equity'],
  [1, 'text', 'excluding_2'],
  [1, 'text', 'not to exceed_2'],
  [1, 'text', 'any financed Funding Fee amortizable monthly for not less than'],
  [1, 'text', 'per annum for the first_3'],
  [1, 'text', 'Text2'],
  [1, 'checkbox', '6 Reverse Mortgage Financing A reverse mortgage loan also known as a Home Equity-1'],
  [1, 'text', 'excluding_2-1'],
  [1, 'text', 'not to exceed-1'],
  [1, 'text', 'any financed Funding Fee amortizable monthly for not less than-1'],
  [1, 'text', 'not to exceed_2-1'],
  [1, 'text', 'per annum for the first_3-1'],
  [1, 'checkbox', 'will'],
  [1, 'checkbox', 'will-1'],
  [1, 'checkbox', 'will-2'],
];

const TREC_49_1_EMBEDDED_FIELDS: readonly EmbeddedField[] = [
  [1, 'text', 'Street Address and City'],
  [1, 'checkbox', '1 WAIVER Buyer w aives Buyers right to terminate the contract under Paragraph 2B of the'],
  [1, 'checkbox', '2 PARTIAL WAIVER Buyer w aives Buyers right to terminate the contract under Paragraph 2B'],
  [1, 'checkbox', '3 ADDITIONAL'],
  [1, 'text', 'ii the opinion of value is'],
  [1, 'text', 'days after the Effective Date if'],
  [1, 'text', 'than'],
  [1, 'text', 'Signature1'],
  [1, 'text', 'Signature2'],
  [1, 'text', 'Signature3'],
  [1, 'text', 'Signature4'],
];

export const TREC_40_11_FIELDS = buildFields('40-11', TREC_40_11_EMBEDDED_FIELDS);
export const TREC_49_1_FIELDS = buildFields('49-1', TREC_49_1_EMBEDDED_FIELDS);
