#!/usr/bin/env bash
#
# DigitalOcean Postgres → Neon data migration.
#
# Prerequisites (set in your shell):
#   DO_DATABASE_URL   — source (the live droplet's managed-pg connection string)
#   NEON_DATABASE_URL — destination (Neon connection string with WRITE access)
#
# Usage:
#   scripts/migrate-do-to-neon.sh --audit   # dry-run: list DO tables, show
#                                           # which candidate tables exist /
#                                           # are missing. NO writes.
#   scripts/migrate-do-to-neon.sh           # real run: dump+restore+verify
#                                           # (only existing tables migrated)
#
# What the real run does:
#   1. Probes DO for each candidate table; logs which exist and which don't
#   2. Dumps existing droplet tables to /tmp/do_dump.sql (data + schema)
#   3. Restores into Neon
#   4. Runs sanity row-count comparisons for each migrated table
#
# Candidate table set was generated by grepping every table referenced from
# lib/server/*.ts and app/api/**/route.ts. Tables that do NOT exist on the
# droplet are skipped (some are Next.js-era additions that only live in Neon).
#
# Run this AFTER deploying the api-merge branch but BEFORE flipping prod traffic
# so live writes during cutover are minimal. Brief read-only window required
# for the dump phase (typically <60s for our data volume).

set -euo pipefail

: "${DO_DATABASE_URL:?DO_DATABASE_URL must be set}"
: "${NEON_DATABASE_URL:?NEON_DATABASE_URL must be set}"

MODE="${1:-run}"

DUMP=/tmp/do_dump.sql

# Candidate set: every table that the Next.js app reads or writes.
# Sourced from `grep -rnE "FROM|INTO|UPDATE|DELETE FROM" lib/server app/api`.
# Some of these tables may not exist on DO (added later, Neon-only) — the
# pre-flight probe will skip those.
CANDIDATE_TABLES=(
  # --- core auth / identity ---
  admins
  realtors
  admin_audit_log
  admin_password_resets
  password_reset_tokens
  magic_links
  webauthn_credentials
  webauthn_challenges
  notification_preferences
  email_log
  # --- giveaways ---
  giveaways
  giveaway_rules
  giveaway_entries
  # --- events ---
  events
  event_rsvps
  # --- ads ---
  ad_spaces
  ad_creatives
  ad_campaigns
  advertisers
  advertiser_email_grants
  # --- magazines ---
  magazines
  magazine_hotspots
  magazine_hotspot_clicks
  thumbnail_jobs
  # --- misc ---
  builder_inventory
  print_subscribers
  notification_deliveries
)

# Probe DO: split CANDIDATE_TABLES into EXISTING and MISSING.
echo "==> Probing DO for ${#CANDIDATE_TABLES[@]} candidate tables..."
EXISTING=()
MISSING=()
for t in "${CANDIDATE_TABLES[@]}"; do
  exists=$(psql "$DO_DATABASE_URL" -tAc \
    "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='$t'" \
    2>/dev/null || echo "")
  if [ "$exists" = "1" ]; then
    EXISTING+=("$t")
  else
    MISSING+=("$t")
  fi
done

echo
echo "    Existing on DO  (${#EXISTING[@]}):"
for t in "${EXISTING[@]}"; do echo "      ✓ $t"; done
echo "    Missing from DO (${#MISSING[@]}, will be skipped — make sure they're not needed):"
for t in "${MISSING[@]}"; do echo "      · $t"; done
echo

# Also surface any tables present on DO that are NOT in our candidate list —
# the app won't query them, but they might still hold data someone cares about.
echo "==> Tables present on DO but NOT in candidate set (review manually):"
ALL_DO_TABLES=$(psql "$DO_DATABASE_URL" -tAc \
  "SELECT table_name FROM information_schema.tables WHERE table_schema='public' ORDER BY table_name" \
  2>/dev/null || echo "")
for t in $ALL_DO_TABLES; do
  found=0
  for c in "${CANDIDATE_TABLES[@]}"; do
    if [ "$c" = "$t" ]; then found=1; break; fi
  done
  if [ "$found" = "0" ]; then
    rows=$(psql "$DO_DATABASE_URL" -tAc "SELECT count(*) FROM \"$t\"" 2>/dev/null || echo "?")
    echo "      ? $t  (rows: $rows)"
  fi
done
echo

if [ "$MODE" = "--audit" ] || [ "$MODE" = "audit" ]; then
  echo "==> Audit complete. No changes made."
  echo "    Re-run without --audit to perform the migration."
  exit 0
fi

if [ "${#EXISTING[@]}" -eq 0 ]; then
  echo "ERROR: No candidate tables found on DO. Aborting." >&2
  exit 1
fi

echo "==> Dumping ${#EXISTING[@]} tables from DO Postgres..."
TBL_FLAGS=()
for t in "${EXISTING[@]}"; do
  TBL_FLAGS+=("-t" "$t")
done

pg_dump \
  --no-owner \
  --no-privileges \
  --if-exists \
  --clean \
  "${TBL_FLAGS[@]}" \
  "$DO_DATABASE_URL" \
  > "$DUMP"

echo "    Dump size: $(du -h "$DUMP" | cut -f1)"

echo "==> Restoring into Neon..."
psql "$NEON_DATABASE_URL" -v ON_ERROR_STOP=1 -f "$DUMP"

echo "==> Comparing row counts..."
printf "%-30s %12s %12s %s\n" TABLE DO NEON STATUS
for t in "${EXISTING[@]}"; do
  do_count=$(psql "$DO_DATABASE_URL" -tAc "SELECT count(*) FROM $t" 2>/dev/null || echo "ERR")
  neon_count=$(psql "$NEON_DATABASE_URL" -tAc "SELECT count(*) FROM $t" 2>/dev/null || echo "ERR")
  if [ "$do_count" = "$neon_count" ]; then
    status="✓"
  else
    status="✗ MISMATCH"
  fi
  printf "%-30s %12s %12s %s\n" "$t" "$do_count" "$neon_count" "$status"
done

echo
echo "==> Done. If all rows match, you can now:"
echo "    1. Update Vercel env: drop DO_DATABASE_URL and NEXT_PUBLIC_API_URL"
echo "    2. Redeploy"
echo "    3. Verify with /api/ready"
echo "    4. Decommission the droplet + DO managed-pg"
