#!/usr/bin/env bash
#
# DigitalOcean Postgres → Neon data migration.
#
# Prerequisites (set in your shell):
#   DO_DATABASE_URL   — source (the live droplet's managed-pg connection string)
#   NEON_DATABASE_URL — destination (Neon connection string with WRITE access)
#
# Usage:
#   scripts/migrate-do-to-neon.sh --audit   # dry-run: list DO tables, show
#                                           # which candidate tables exist /
#                                           # are missing. NO writes.
#   scripts/migrate-do-to-neon.sh           # real run: dump+restore+verify
#                                           # (only existing tables migrated)
#
# What the real run does:
#   1. Probes DO for each candidate table; logs which exist and which don't
#   2. Dumps existing droplet tables to /tmp/do_dump.sql (data + schema)
#   3. Restores into Neon
#   4. Runs sanity row-count comparisons for each migrated table
#
# Candidate table set was generated by grepping every table referenced from
# lib/server/*.ts and app/api/**/route.ts. Tables that do NOT exist on the
# droplet are skipped (some are Next.js-era additions that only live in Neon).
#
# Run this AFTER deploying the api-merge branch but BEFORE flipping prod traffic
# so live writes during cutover are minimal. Brief read-only window required
# for the dump phase (typically <60s for our data volume).

set -euo pipefail

: "${DO_DATABASE_URL:?DO_DATABASE_URL must be set}"
: "${NEON_DATABASE_URL:?NEON_DATABASE_URL must be set}"

MODE="${1:-run}"

DUMP=/tmp/do_dump.sql

# Candidate set: every table that the Next.js app reads or writes that lives
# ONLY on DO. Tables that already exist on Neon with DIFFERENT schemas
# (events, advertisers) are explicitly excluded — they'd corrupt Neon's
# Next.js-era data. DO copies of those are empty anyway.
#
# Sourced from `grep -rnE "FROM|INTO|UPDATE|DELETE FROM" lib/server app/api`,
# minus the exclusions above.
CANDIDATE_TABLES=(
  # --- core auth / identity (DO-only) ---
  admins
  realtors
  admin_audit_log
  admin_password_resets
  password_reset_tokens
  magic_links
  webauthn_credentials
  webauthn_challenges
  notification_preferences
  email_log
  # --- giveaways (DO-only) ---
  giveaways
  giveaway_rules
  giveaway_entries
)

# Tables explicitly NOT migrated from DO because Neon owns them with a
# different schema or the FK target doesn't match. The migration must not
# touch these.
# - events       : Neon = event listings (177 rows, INT id); DO = empty UUID schema
# - advertisers  : Neon = advertiser directory (20 rows, INT id); DO = empty UUID schema
# - event_rsvps  : 0 rows on DO; FK targets DO events(UUID id) which can't be
#                  resolved on Neon. If event RSVP feature is rebuilt, it'll
#                  need a fresh schema against Neon's events table.
# - notifications, notification_deliveries: 0 rows on DO; have FKs to DO
#                  advertisers(UUID). Created manually below WITHOUT those
#                  FKs since the Next.js code only does DELETE cascades on
#                  realtor removal.

# Probe DO: split CANDIDATE_TABLES into EXISTING and MISSING.
echo "==> Probing DO for ${#CANDIDATE_TABLES[@]} candidate tables..."
EXISTING=()
MISSING=()
for t in "${CANDIDATE_TABLES[@]}"; do
  exists=$(psql "$DO_DATABASE_URL" -tAc \
    "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='$t'" \
    2>/dev/null || echo "")
  if [ "$exists" = "1" ]; then
    EXISTING+=("$t")
  else
    MISSING+=("$t")
  fi
done

echo
echo "    Existing on DO  (${#EXISTING[@]}):"
for t in "${EXISTING[@]}"; do echo "      ✓ $t"; done
echo "    Missing from DO (${#MISSING[@]}, will be skipped — make sure they're not needed):"
for t in "${MISSING[@]}"; do echo "      · $t"; done
echo

# Also surface any tables present on DO that are NOT in our candidate list —
# the app won't query them, but they might still hold data someone cares about.
echo "==> Tables present on DO but NOT in candidate set (review manually):"
ALL_DO_TABLES=$(psql "$DO_DATABASE_URL" -tAc \
  "SELECT table_name FROM information_schema.tables WHERE table_schema='public' ORDER BY table_name" \
  2>/dev/null || echo "")
for t in $ALL_DO_TABLES; do
  found=0
  for c in "${CANDIDATE_TABLES[@]}"; do
    if [ "$c" = "$t" ]; then found=1; break; fi
  done
  if [ "$found" = "0" ]; then
    rows=$(psql "$DO_DATABASE_URL" -tAc "SELECT count(*) FROM \"$t\"" 2>/dev/null || echo "?")
    echo "      ? $t  (rows: $rows)"
  fi
done
echo

if [ "$MODE" = "--audit" ] || [ "$MODE" = "audit" ]; then
  echo "==> Audit complete. No changes made."
  echo "    Re-run without --audit to perform the migration."
  exit 0
fi

if [ "${#EXISTING[@]}" -eq 0 ]; then
  echo "ERROR: No candidate tables found on DO. Aborting." >&2
  exit 1
fi

echo "==> Dumping ${#EXISTING[@]} tables from DO Postgres..."
TBL_FLAGS=()
for t in "${EXISTING[@]}"; do
  TBL_FLAGS+=("-t" "$t")
done

# Ensure required extensions and enum types exist on Neon BEFORE the dump
# tries to reference them. pg_dump -t doesn't include type definitions, so
# we extract them manually.
echo "==> Ensuring citext extension on Neon..."
psql "$NEON_DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL' > /dev/null
SET search_path TO public;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
SQL

echo "==> Extracting enum types from DO..."
ENUM_DDL=$(psql "$DO_DATABASE_URL" -t -A <<'SQL'
SELECT 'CREATE TYPE public.' || t.typname || ' AS ENUM (' ||
  string_agg(quote_literal(e.enumlabel), ',' ORDER BY e.enumsortorder) || ');' AS ddl
FROM pg_type t
JOIN pg_enum e ON t.oid = e.enumtypid
JOIN pg_namespace n ON n.oid = t.typnamespace
WHERE n.nspname = 'public'
GROUP BY t.typname
ORDER BY t.typname;
SQL
)
echo "    $(echo "$ENUM_DDL" | wc -l | tr -d ' ') enum type(s) found"

echo "==> Creating enum types on Neon (skipped if already present)..."
psql "$NEON_DATABASE_URL" <<EOF > /dev/null 2>&1 || true
SET search_path TO public;
$ENUM_DDL
EOF

# CRITICAL: do NOT use --clean. Earlier versions used --clean which generated
# DROP TABLE statements that would have wiped Neon's existing Next.js-era
# tables (magazines, advertisers, events, builder_inventory, etc.). Since the
# candidate set is now restricted to DO-only tables, we just append.
pg_dump \
  --no-owner \
  --no-privileges \
  "${TBL_FLAGS[@]}" \
  "$DO_DATABASE_URL" \
  > "$DUMP"

echo "    Dump size: $(du -h "$DUMP" | cut -f1)"

echo "==> Restoring into Neon..."
psql "$NEON_DATABASE_URL" -v ON_ERROR_STOP=1 -f "$DUMP"

echo "==> Creating notifications + notification_deliveries (FK-stripped, empty)..."
psql "$NEON_DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL' > /dev/null
SET search_path TO public;
CREATE TABLE IF NOT EXISTS notifications (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category        notification_category_enum NOT NULL,
  title           text NOT NULL,
  body            text NOT NULL,
  deep_link_url   text,
  target_audience jsonb NOT NULL DEFAULT '{}'::jsonb,
  advertiser_id   uuid,                          -- no FK; DO advertisers schema not migrated
  scheduled_for   timestamptz,
  sent_at         timestamptz,
  status          notification_status_enum NOT NULL DEFAULT 'draft',
  created_by      uuid,                          -- soft-ref to admins(id)
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS notification_deliveries (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  realtor_id      uuid NOT NULL REFERENCES realtors(id)     ON DELETE CASCADE,
  channel         notification_channel_enum NOT NULL,
  delivered_at    timestamptz,
  opened_at       timestamptz,
  clicked_at      timestamptz,
  failure_reason  text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notification_deliveries_notification_id_index
  ON notification_deliveries(notification_id);
CREATE INDEX IF NOT EXISTS notification_deliveries_realtor_id_index
  ON notification_deliveries(realtor_id);
SQL

echo "==> Comparing row counts..."
printf "%-30s %12s %12s %s\n" TABLE DO NEON STATUS
for t in "${EXISTING[@]}"; do
  do_count=$(psql "$DO_DATABASE_URL" -tAc "SELECT count(*) FROM $t" 2>/dev/null || echo "ERR")
  neon_count=$(psql "$NEON_DATABASE_URL" -tAc "SELECT count(*) FROM $t" 2>/dev/null || echo "ERR")
  if [ "$do_count" = "$neon_count" ]; then
    status="✓"
  else
    status="✗ MISMATCH"
  fi
  printf "%-30s %12s %12s %s\n" "$t" "$do_count" "$neon_count" "$status"
done

echo
echo "==> Done. If all rows match, you can now:"
echo "    1. Update Vercel env: drop DO_DATABASE_URL and NEXT_PUBLIC_API_URL"
echo "    2. Redeploy"
echo "    3. Verify with /api/ready"
echo "    4. Decommission the droplet + DO managed-pg"
